### ISSUE TITLE
Module Prim.Boolean was not found

### ISSUE THREAD

**Issue by kedashoe** [spacchetti/spago#103]
I'm not sure exactly what brought in typelevel-prelude (I was trying to use Halogen), but I am getting this error.

```bash
in module Type.Data.Boolean
at .spago/typelevel-prelude/v4.0.0/src/Type/Data/Boolean.purs line 17, column 1 - line 17, column 48

  Module Prim.Boolean was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.
```
I tried from a fresh project, `spago init`, `spago upgrade-spacchetti`, `spago install typelevel-prelude`, `spago test` and still go the error. I tried the latest release of spago and building from source.

**Comment by justinwoo** [comment]
you need purescript 0.12.2

**Comment by justinwoo** [comment]
see release notes here: https://github.com/purescript/purescript/releases/tag/v0.12.2

> Add Boolean kind to Prim.Boolean

**Comment by f-f** [comment]
@kedashoe currently Spago doesn't check if the compiler version is compatible with the package-set: in this case you had purs v0.12.1, but the package-set is for v0.12.2.

Spago should warn in these cases, and this is tracked in #101

**Comment by kedashoe** [comment]
Thanks for the quick response, that fixed it!

I'll close this since you are already tracking it
