### ISSUE TITLE
Remove `"some-package" already installed` message

### ISSUE THREAD

**Issue by starper** [spacchetti/spago#114]
Since `build` now is trying to install packages before building a module, every time it's called we end up with a lot of `"some-package" already installed` messages (73 in my case). To be honest, I'm not sure I'm interested in what is already installed even when I call `install`, but maybe someone is, so it's ok. But seeing this messages every time you call `build` is a bit irritating.

**Comment by f-f** [comment]
@starper this should be fixed in #112

**Comment by i-am-the-slime** [comment]
Any chance you could make a release with this change in it?

**Comment by f-f** [comment]
@i-am-the-slime yes, I'll release 0.7 later today :)

**Comment by f-f** [comment]
@i-am-the-slime [0.7 is now released! 🎉](https://github.com/spacchetti/spago/releases/tag/0.7.0.0)

**Comment by i-am-the-slime** [comment]
Just tried it. So good, thanks for this great piece of software, Fabrizio!

**Comment by f-f** [comment]
Thanks for the kind words 🙂
