### ISSUE TITLE
Remote path is parsed as local one

### ISSUE THREAD

**Issue by starper** [spacchetti/spago#119]
`spago` parses `git@foo.com:bar/baz.git` as a local path

**Comment by f-f** [comment]
The reason why this happens is that there's no protocol in front of the url (it should be `git://` in this case), and this confuses `Network.URI.parseURI` that we use for parsing the remotes.

The rule of thumb should be that we "classify as remote" any URL that `git clone` would accept (in this case, this is accepted).
So here we could either require the protocol (rejecting your url as a `Remote` one, but we should then define some guidelines), or try to parse this as a git URL.

In any case, I'd consider this a bug

**Comment by starper** [comment]
@f-f I think requiring a protocol is a better solution, but there should be a note somewhere in docs, saying that, when using `ssh`, people should not mindlessly copy and paste `git@foo.com:bar/baz.git` (as I did), but should rewrite it as `ssh://git@foo.com/bar/baz.git`.

**Comment by f-f** [comment]
@starper agreed 👍 

Let's add an entry to the FAQ (or mention it somewhere else in the README) and I'll reclassify this issue as a documentation issue
