### ISSUE TITLE
Problem with a "clean" install of Halogen

### ISSUE THREAD

**Issue by gcsolaroli** [spacchetti/spago#123]
I am trying out Purescript using Spago following along the Halogen documentation.
I am having some troubles doing a full install from a freshly checkout workarea.
I think I have been able to reproduce the problem; or I am making a terrible mistake.

# My environment

    $ nvm current
    v10.15.2
    $ purs --version
    0.12.3
    $ spago version
    0.7.0.0

# Steps to reproduce the problem

    $ mkdir spago-install-issue
    $ cd spago-install-issue
    $ spago init
    $ spago install
    $ spago install halogen
    -- so far, so good; now to simulate a fresh checkout/clone I remove the .spago folder
    $ rm -rf .spago
    $ spago install
    spago: Installation failed.

Are my expectation about a "fresh install" wrong, or is this an actual issue?

Doing the same procedure with other libraries (I have tried with 'affjax' and 'random') seems to work fine.

After the installation failure, running the `spago install` command will report "Installation complete.", but a `spago build` done afterward will raise tons of errors.

**Comment by f-f** [comment]
Hi @gcsolaroli, thanks for the report :)

The steps you listed look good, but I cannot reproduce the problem on my macOS and Linux machines, with the same versions of spago and purs 🤔 - the second `install` doesn't fail, and the subsequent `build` works properly

Which OS are you on?

**Comment by gcsolaroli** [comment]
I had the problem on my personal iMac Pro with latest version of MacOS.
I have just tried the same steps with my office computer (iMac with MacOS 10.12.6) and everything works as expected. 🤔
I will try to investigate it further when back at home.

**Comment by f-f** [comment]
Thinking more about it, this looks like a non-deterministic test failure we get sometimes, e.g. [see this build log](https://travis-ci.com/spacchetti/spago/jobs/174973199). For some reason the install is totally bypassed, so the compiler doesn't find the modules and it fails. And that happens only on macOS, the Linux CI never had that problem. So far I have not been able to reproduce that failure on my mac 🙁 

So if this is the same bug, and it reproduces fine on your machine, I'd say we have a good lead to track this 🙂

**Comment by gcsolaroli** [comment]
Unfortunately I will be able to check it only later tonight.
I would love to be somehow helpful (even if just passively providing some info or test environment) in fixing a problem. 😃

**Comment by gcsolaroli** [comment]
# My environment
    
    $ system_profiler SPSoftwareDataType
    Software:
    
        System Software Overview:
    
          System Version: macOS 10.14.3 (18D109)
          Kernel Version: Darwin 18.2.0
          Boot Volume: Macintosh HD
          Boot Mode: Normal
          Computer Name: iMac Pro
          User Name: Giulio Cesare Solaroli (giulio.cesare)
          Secure Virtual Memory: Enabled
          System Integrity Protection: Enabled
          Time since boot: 16 minutes
    
    $ nvm --version
    0.33.11
    $ npm --version
    6.4.1
    $ node --version
    v10.15.2
    $ purs --version
    0.12.3
    $ spago version
    0.7.0.0

Is there anything else relevant for defining the environment?

What I consistently get is that these steps always succeed:

    $ mkdir test; cd test
    $ spago init
    $ spago install
    $ spago install halogen
    $ cd ..; rm -rf test

Instead these steps consistently fails:

    $ mkdir test; cd test
    $ spago init
    $ spago install halogen
    spago: Installation failed.
    $ cd ..; rm -rf test

Unfortunately I have not been able to find a more detailed log of the installation procedure, so I don't know how to further investigate the issue.
I have tried to `diff` the `.spago` folder created in the two cases, but being most of the files binary, the output is pretty much useless (at least to my eyes).

Any idea on how I could further investigate this issue?

**Comment by f-f** [comment]
Unfortunately I still cannot reproduce on my machine, but it's super great that we have a reproduction on yours! 🎉 

It looks like you run into one of the places in which we have insufficient error reporting :(
I just pushed a [fix for that](https://github.com/spacchetti/spago/commit/daf902379284f71946f703897738365634a1a850), and I compiled this new version for you so you can try the fix without building the project. You can download it [_here_](https://github.com/spacchetti/spago/files/2933276/spago.zip)

With this new version it should print something more than just "Installation failed", let's hope to get something useful :)

**Comment by gcsolaroli** [comment]
spago: Installation failed.

Error:

.spago/unfoldable/v4.0.0: openDirStream: resource exhausted (Too many open files)

**Comment by f-f** [comment]
@gcsolaroli wonderful, that's a helpful message! It looks like spago is reaching the limit of open files per process in your OS.

It turns out I have quite high limits for them on my machine, so that's why I wasn't able to replicate. The following command sets the limit for open files to 50 per process:

```
$ ulimit -n 50
```

This allows for reproducing reliably on my machine too:

```
$ spago install halogen
...
Installing "unsafe-reference"
Installing "web-clipboard"
Installing "web-file"
Installing "web-events"
Installing "web-touchevents"
spago: Installation failed.

Error:

.spago/functors/v3.1.1: openDirStream: resource exhausted (Too many open files)
```

We have the flag `--jobs` to limit concurrency for install operations exactly for cases like this in which one has not enough open files available. So this should be fixable by just adding the flag!

...However, it looks like a low enough setting in `ulimit` uncovers a bug in the `async-pool` library (that we're using for pooling async operations), for which the library doesn't respect the limit that we give it for the size of the task pool, and just creates as many asyncs as it needs (and the reason why this happens with Halogen is that it has to install ~70 libraries, and they each spawn a thread), somehow saturating the limit of open processes. I'll open an issue there.

In the meanwhile let's see if we can get some more progress, so I'll give you some more commands to run:
- Does `spago install -j 20 halogen` solve the issue?
- What's the result of running `ulimit -a`?

**Comment by gcsolaroli** [comment]
This is the setup of my home iMac Pro

```
$ launchctl limit
	cpu         unlimited      unlimited      
	filesize    unlimited      unlimited      
	data        unlimited      unlimited      
	stack       8388608        67104768       
	core        0              unlimited      
	rss         unlimited      unlimited      
	memlock     unlimited      unlimited      
	maxproc     5674           8512           
	maxfiles    256            unlimited      

$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 5674
virtual memory          (kbytes, -v) unlimited
```

My office iMac instead has these settings:
```
$ launchctl limit
	cpu         unlimited      unlimited      
	filesize    unlimited      unlimited      
	data        unlimited      unlimited      
	stack       8388608        67104768       
	core        0              unlimited      
	rss         unlimited      unlimited      
	memlock     unlimited      unlimited      
	maxproc     709            1064           
	maxfiles    256            unlimited      

$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 2560
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

I don't remember having changed explicitly any of these settings on either computer.

Running the `install` command with the `-j 10` option works flawlessly. 👍 

The highest value of `concurrent jobs` that can reliably succeed in building the project on my computer is **71**; with higher values, it fails.

To me, having a workaround to build the project is more than enough.
But if I can provide further help in investigating the issue, I would be pleased to help.

THANKS!

**Comment by f-f** [comment]
Happy to hear the flag is working for you! I investigated this some more and it looks like the problem I was running into is not a bug in the library, but just the flag value not being low enough. I will leave this issue open to track more investigation and/or a better error message.

Grazie mille per l'aiuto Giulio! 🙂

**Comment by gcsolaroli** [comment]
> Grazie mille per l'aiuto Giulio! 🙂

I have to thanks you and @justinwoo for all the hard work done lately to make purescript tooling so nice to use.
And now that my build outcome is deterministic again, I can keep on studying purescript and halogen.
