### ISSUE TITLE
Confusion around purescript-* named packages

### ISSUE THREAD

**Issue by FintanH** [spacchetti/spago#129]
I got confused by following the purescript book and packages were named `purescript-*`. When I tried adding them it would say they're missing. I only realised after a bit of digging that I didn't need the prefix. I didn't spot this in the docs, but maybe I missed it. Should this info be added/made more clear? #noob

**Comment by f-f** [comment]
@FintanH indeed you're right, sorry for the confusion and thanks for reporting 🙂 

Fix up in #130

**Comment by FintanH** [comment]
Thanks @f-f! You've made a Purescript beginner's life that much better :heart:

**Comment by f-f** [comment]
@FintanH happy to hear that! ❤️
