### ISSUE TITLE
`spago run` command

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#131]
Someone was complaining about this, but it's essentially an alias of `test`:

https://github.com/spacchetti/spago/blob/b6d5a6345b056c773c9011768e1914493dd97aec/app/Spago/Build.hs#L62-L70

Only difference would be the labels and that `Main` is used by default.

**Comment by JordanMartinez** [comment]
> Someone was complaining about this

Not sure whether this refers to me. If so, I apologize. I didn't want to come off as "complaining."

**Comment by f-f** [comment]
@JordanMartinez no need to apologize, I'm pretty sure Justin didn't mean it in a negative way 🙂 (source: he uses the word "complaining" quite often IRL for many things in various meanings, and in this case I interpreted it as a general "someone expressed the need for")

**Comment by JordanMartinez** [comment]
Thanks for the clarification. Ah, the ambiguity of language...
