### ISSUE TITLE
Clarification: `spago bundle` does do DCE

### ISSUE THREAD

**Issue by JordanMartinez** [spacchetti/spago#135]
Medium priority. 

Coming from [this comment]():
> spago bundle does include DCE. In fact, make-module is nothing more than doing the bundle and then adding a line of js exporting the Main module, see the source for both here
> So if you wish to "make a module and run it via node", that's just spago bundle.
> If there's a place in our docs that it's misleading about it, it would be lovely if you could open a PR to clarify it somehow :)

Let me explain where my misunderstanding arose first. In [the ReadMe's "building, bundling, and testing a project" section](https://github.com/spacchetti/spago/blob/master/README.md#building-bundling-and-testing-a-project), it states:
> [overview of `spago bundle` command]
>
> _However_, you might want to build a module that has been “dead code eliminated” if you plan to make a single module of your PS exports, which can then be required from JS.
> 
> Gotcha covered:
> [introduces `spago make-module` command]

The way I read that, it seemed to imply that `spago bundle` did not do DCE at all.

**Comment by f-f** [comment]
I'll include a rewording of that section in #125

**Comment by JordanMartinez** [comment]
Ok. Thanks.

**Comment by f-f** [comment]
@JordanMartinez fix for this in [this commit](https://github.com/spacchetti/spago/pull/125/commits/0b8ce35ebe6bd716e26045fd35b8b61ebcb4f8b3)

Would this wording work?

**Comment by JordanMartinez** [comment]
That wording is definitely much clearer on the DCE stuff. Thanks!
