### ISSUE TITLE
`spago verify` command

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#14]
Need a verify command that will attempt to install and build a given dependency. This can be done in almost any way, but a full set verify should install one package while verifying at a time.

**Comment by f-f** [comment]
I'll try to clarify the spec for this: the command would be `spago verify $package-name`, and what would happen is that we would:
- read the package set
- lookup if the `package-name` is in the set
- if yes, get the list of its dependencies, and for each of them:
  - try to install it
  - try to build it
  - recursively do this thing of looking up, installing and building deps (this will in the end cover all the transitive dependencies of the main package)
