### ISSUE TITLE
Be explicit about the "thin layer"

### ISSUE THREAD

**Issue by JamieBallingall** [spacchetti/spago#143]
The README says that `spago build` is "...just a thin layer above the PureScript compiler command purs compile." 

It would be lovely to be explicit in the README about what purs command would replicate `spago build`.

This request is partially driven by that fact that Spago is being recommended quite often in the purescript-beginners Slack channel. So new users of Spago may be new users of Purescript and may not have a lot of existing Purescript familiarity.

**Comment by f-f** [comment]
Great point! In [this issue](https://github.com/JordanMartinez/purescript-jordans-reference/issues/194#issuecomment-472832300) we already figured out with @JordanMartinez that it would be actually useful (for inspectability reasons) to have spago print out which `purs` command it is calling

**Comment by JamieBallingall** [comment]
That's a better solution.

The issue you reference is on another project. Does it make sense to break it up into separate issues on this project?

I'm happy to read through and try to create those issues here. I'm trying to be as useful as possible without actually touching the code.

**Comment by f-f** [comment]
@JamieBallingall thanks! But no worries, we already addressed most of the issues from there, and I'll open some PRs later to address the missing ones 🙂
