### ISSUE TITLE
Rename `spago bundle` and `spago make-module`

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#147]
These two commands do basically the same thing but have different enough names to be confusing.

So we should rename them to something clearer. Proposals:
1. `spago bundle-app`, `spago bundle-module`
2. `spago bundle app` `spago bundle module`
3. `spago bundle` defaults to "app" mode, and the module functionality is behind a flag `spago bundle --module`

**Comment by FintanH** [comment]
My vote would be 2. 👍 👍

**Comment by FintanH** [comment]
> `--main` it to specify the main module that gets exposed (either to run or to export)

So I understand you're pointing to the `--main` module but it seems like a strange mnemonic to me for bundling a module. Does the module _have_ to be a `module Main`?

**Comment by f-f** [comment]
@FintanH it doesn't have to be, but I hear you that this flag might be misnamed. If you do `spago bundle --help`, it gets a bit cleared as it tells you what it is for: 
```
-m,--main MAIN           The main module to bundle
```

However, this same flag is `--module` in `purs`, so I'd support renaming it to `--module` here too

**Comment by FintanH** [comment]
> The main module to bundle

I think that's still ambiguous because it says "main" 😄 

`--module` is good, my only gripe is that it's repetitive if we go down the route of `spago bundle module`. But I have no better alternative 👍
