### ISSUE TITLE
Provide a way to get dependency licenses

### ISSUE THREAD

**Issue by i-am-the-slime** [spacchetti/spago#150]
This is something we need in order to comply with GDPR if we want to switch to Spago.

**Comment by f-f** [comment]
@i-am-the-slime how should this work?

I.e. would something like `cat $(find .spago -iname 'LICENSE')` be enough?

**Comment by i-am-the-slime** [comment]
I think something along those lines could work. Sounds like it could be a separate tool then. It would be nice to not include transitive dependencies if possible. That would involve parsing some spago or packages files for filtering, I guess.

**Comment by f-f** [comment]
@i-am-the-slime you can get various lists of packages, versions, etc with the `list-packages` command.

It has a `--filter` flag, so in this case we can do `spago list-dependencies --filter direct` to get only the direct dependencies.

Building on the bash example above we get:
```bash
#!/bin/bash

# Note: the `awk` part is to cut out only the package name
for dep in $(spago list-packages -f direct | awk '{print $1}')
do
  cat $(find ".spago/${dep}" -iname 'LICENSE')
done
```

I'd like to avoid baking this kind of functionality into Spago, as:
1. it's achievable with some lines of bash vs more lines into Spago
2. the desidered output might not be the same for different cases, so this way of doing it provides maximum flexibility (as you can tweak formatting, etc as desired)

**Comment by Ivewinne** [comment]
11

**Comment by i-am-the-slime** [comment]
This is very nice, thank you very much.

**Comment by f-f** [comment]
@i-am-the-slime you're welcome! 🙂 

I think this is a useful bit of information worth adding to the FAQ, so I'll add the "docs" label and keep this open

**Comment by wires** [comment]
Many package managers (`cargo`, `elba`, `npm`) allow you to specify the license in the package manifest, usually by specifying a `license` field which has some [SPDX](https://spdx.org/licenses/) identifier as value.

Maybe it is a good idea to follow this approach?

**Comment by f-f** [comment]
@wires in this case we're talking about getting license information from dependencies, which at the time of writing are going to be 100% bower projects. So this means adapting the above bash snippet to call `jq` to extract the `license` field from the bower config instead of printing the license file.

I'm open to adding a `license` field to our config, but I'd say we should discuss it in another issue
