### ISSUE TITLE
Print failures below successes?

### ISSUE THREAD

**Issue by JamieBallingall** [spacchetti/spago#152]
There is a laudable willingness on this project to discuss UX issues. This is a fairly minor one but I thought I would throw it out there.

In an empty directory run:
```
spago init
spago install halogen
```
All works as expected. Then run
```
spago install does-not-exist
```
As expected, the install of `does-not-exist` fails and a warning message is printed. However, immediately afterward we get
```
Installing 72 dependencies.
"avar" already installed
"bifunctors" already installed
...
```
Since there are 72 of them (Halogen is a big package), the warning message about `does-not-exist` is immediately pushed off the top of the screen. This makes it very easy to miss. And in this particular use of `spago install` it was the whole point of running the command. I recognize that is not always the case but it is sometimes the case.

The simplest answer would be to move the warning to after the successfully installed dependencies. Alternatively (or in addition) the messages about already installed packages could be abbreviated into `72 dependencies already installed. Run spago install --verbose to see the list`. Also maybe some color in the failure warning would be nice.

**Comment by f-f** [comment]
@JamieBallingall are you on the latest release? (i.e. `0.7.0`)

The "$dependency already installed" messages should be gone, and the command fails if you try installing a dependency that doesn't exist:

```
$ spago install halogen does-not-exist
spago: Package `does-not-exist` does not exist in package set
```

(this wording is not released yet, but the old wording is basically the same and the command fails as well)

**Comment by JamieBallingall** [comment]
Ah. Ok. The new output looks great.
