### ISSUE TITLE
Handling of the `packages` config key is surprising

### ISSUE THREAD

**Issue by jmackie** [spacchetti/spago#158]
Suppose I have a project that contains several PureScript apps. I'd like to use `spago` to pin a single package set (+ additions and overrides) and have all my apps pull dependencies from that set. I'd like/expect my directory structure to look like

```
.
├── A
│   ├── spago.dhall
│   ├── src
│   │   └── Main.purs
│   └── test
│       └── Main.purs
├── B
│   ├── spago.dhall
│   ├── src
│   │   └── Main.purs
│   └── test
│       └── Main.purs
└── packages.dhall
```

Where `A/spago.dhall` looks something like:

```
{ name =
    "A"
, dependencies =
    [ "effect", "console" ]
, packages =
    ./../packages.dhall
}
```

But when I run `spago build` inside `A` a fresh `packages.dhall` is generated in that directory. 

It turns out that setting the `packages` key to anything other than `./packages.dhall` is kinda redundant, which I understand is for `psc-package` interop reasons. 

In order to achieve what I want (correct me if I'm wrong here) I'd have to have change `A/spago.dhall` to the standard:

```
{ name =
    "A"
, dependencies =
    [ "effect", "console" ]
, packages =
    ./packages.dhall
}
```

Then `A/packages.dhall` should just reference the shared package set

```
./../packages.dhall
```

Which isn't bad, just a bit unexpected. 

Discuss :)

**Comment by f-f** [comment]
@jmackie analysis perfectly on point :)

The context here is that we have two different config files for several reasons:
- easily supporting the generation of a `packages.json` file for `psc-package` (by doing `cat packages.dhall | dhall-to-json > packages.json`
- separation of concerns: `spago.dhall` talks about your project, and `packages.dhall` talks about the package set
- Given the above, I'm worried that having all the config in the same file might end up too verbose or confusing or both
- Dhall currently doesn't preserve comments in the middle of the file (a fix for that is coming), so having an additional file means not having to cram all the explanations in the same file header

However, all the above reasons are not that strong, and I think the two files can be unified in the future (main blocker: #165)

In the meanwhile we can think of some way to avoid creating a package set file every time.
An idea could be to evaluate the `spago.dhall`, and check if the `packages` key contains a non-empty `Map`. If yes, we can be pretty sure the config is importing some package set file
