### ISSUE TITLE
Strange message

### ISSUE THREAD

**Issue by starper** [spacchetti/spago#160]
I'm using spago `v0.7.2.0`, purs `v0.12.3` and the latest package-set `psc-0.12.3-20190323-2`. Everything is ok, except for this strange message that keeps popping up, saying:
```
WARNING: the package-set version you're on doesn't check if the version of the
PureScript compiler installed on your system is compatible.
If your build fails you might want to upgrade your set by running this command:
`spago package-set-upgrade`
```
My guess is that spago gets confused by this `-2` in the end of a package-set name. If this is the case then maybe it would be better to change current format from `psc-version-date` to `psc-version-date-x` (where `x` stands for `0`, `1`, `2` and so on), to be more explicit about the fact that it is possible to have more then one release in one day.

**Comment by f-f** [comment]
@starper good catch! Fix up in #161

**Comment by starper** [comment]
@f-f What do you think about changing package-set version format from `psc-version-date` to `psc-version-date-x`?

**Comment by f-f** [comment]
@starper I have no opinion on it. While it's not optimally consistent, it's consistent enough so that the clients can use it, so it's good by me :)

**Comment by f-f** [comment]
@starper new release with the fix: https://github.com/spacchetti/spago/releases/tag/0.7.3.0
