### ISSUE TITLE
Erroneous package-set warning when importing `packages.dhall`

### ISSUE THREAD

**Issue by jmackie** [spacchetti/spago#163]
Spago project:

```
{- spago.dhall 
-}
{ name =
    "my-project"
, dependencies =
    [ "effect", "console" ]
, packages =
    ./packages.dhall
}
```

```
{- packages.dhall

Note that `upstream` references another file

Also note that I'd prefer this file to consist of only `./my-packages.dhall`, but the current
parsing logic doesn't allow that...

-}
let mkPackage =
      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.3-20190312/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57

let upstream = ./my-packages.dhall -- IMPORTANT

let overrides = {=}

let additions = {=}

in  upstream ⫽ overrides ⫽ additions
```

```
{- my-packages.dhall 
-}
let mkPackage =
      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.3-20190312/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57

let upstream =
      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.3-20190312/src/packages.dhall sha256:379a4e0b19b1c1977d053d6cdd9403c579014f2cbdeab8b72700a1ae438b6897

let overrides = {=}

let additions = {=}

in  upstream ⫽ overrides ⫽ additions
```

Running `spago build` throws the following warning:

```
WARNING: the package-set version you're on doesn't check if the version of the
PureScript compiler installed on your system is compatible.
If your build fails you might want to upgrade your set by running this command:
`spago package-set-upgrade`
```

Which I'm pretty sure it shouldn't :)

**Comment by jmackie** [comment]
This kinda relates to #162

**Comment by f-f** [comment]
@jmackie I think you're the first one to try handling a monorepo with Spago, so that's the reason why we're finding some bleeding edges.
However, it's interesting and it's a use case I'd like to support (we also have [a monorepo at work](https://github.com/KSF-Media/affresco)), so let's see what we can do :)

I think I might have addressed this problem in https://github.com/spacchetti/spago/issues/162#issuecomment-476859195, in this paragraph:
> For 2. we need again to search specifically for the remote import of the package-sets repo (because it's the only one that has tags that match our expectations), but we should make a distiction between:
> 1. the case in which we find this remote (assuming we can search through the AST), but the tag doesn't match: then we should error out if needed (but this happens here already
> 2. the case in which we have no idea what's going on (i.e. cannot find the import, or the import is local, etc). Then we should either have a lighter warning or no warning at all
