### ISSUE TITLE
Vim support

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#169]
Talking with @anttih today I learned that Spago is not supported by `psc-ide-vim`, so opening an issue to track this (thanks Antti!)

I also opened an issue upstream: https://github.com/FrigoEU/psc-ide-vim/issues/143

**Comment by johnmendonca** [comment]
In the meantime this just worked for me:

```
spago psc-package-insdhall
ln -s .psc-package/local/.set/packages.json psc-package.json
```

**Comment by f-f** [comment]
@johnmendonca thanks! However I think you'd have to run again `spago psc-package-insdhall` every time you change the package set right?

**Comment by johnmendonca** [comment]
Yes, that sounds right.

**Comment by masaeedu** [comment]
Spago does seem to work with https://github.com/nwolverson/purescript-language-server, which in turn can work with "language service aggregator" plugins like https://github.com/w0rp/ale or https://github.com/neoclide/coc.nvim/. I'm using the latter and it works pretty good!

**Comment by f-f** [comment]
I'll close this as it has been fixed in https://github.com/FrigoEU/psc-ide-vim/pull/145 (which appears to be working nicely and is just waiting for merge) 🎉

Thanks @danieljharvey!
