### ISSUE TITLE
Watch directory dependencies?

### ISSUE THREAD

**Issue by jmackie** [spacchetti/spago#172]
Back at it again with the "workspace" problems...

If I have spago project `A` that depends on spago project `B` (in a sibling directory), it would be nice if `spago build --watch` run from project `A` responded to changes in project `B`. This may not be possible, but just a suggestion :)

See https://github.com/jmackie/spago-issues for a reproducible example of what I'd like to do (that link will probably rot, apologies)

**Comment by f-f** [comment]
I think this would be quite fine to wire in, but I'll think a bit about the implications of this.

However in the meanwhile you can solve this by:
- not having `B` in the dependencies
- ..but instead including its sources with the `--path` option. E.g. in [our monorepo](https://github.com/KSF-Media/affresco) we use the following to build at the top level: `spago build --path "packages/*/src/**/*.purs" --path "apps/*/src/**/*.purs"`

(Btw if you'd like the link to not rot you could make a branch and link to it instead)

**Comment by f-f** [comment]
@jmackie I opened #309 to fix this (and it will work correctly in all cases once #301 gets in too), could you try that branch and see if it works for you?
