### ISSUE TITLE
Add "sources" config key

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#173]
Spago includes some default path globs in the build:
- `src/**/*.purs`
- `test/**/*.purs`

However, if you don't have those directories, it will complain:
```
purs compile: No files found using pattern: src/**/*.purs
purs compile: No files found using pattern: test/**/*.purs
```

I propose we instead make this explicit (and configurable) by adding a `sources` (or `paths`) key to the configuration, and removing the implicit paths.
We should migrate existing configurations so the change is backwards compatible.

**Comment by jmackie** [comment]
+1

**Comment by f-f** [comment]
Related to this: I discovered that `purs build --watch` doesn't work if you are missing one of the defaults folders

**Comment by bbarker** [comment]
Perhaps this can also be disabled somehow, since in the case where one's tests has additional dependencies, it should be structured as a separate project described in https://github.com/spacchetti/spago/#separate-devdependencies-or-test-dependencies ?

**Comment by f-f** [comment]
@bbarker Once we enable this you'd explicitly have the globs in your `spago.dhall`, e.g. for a test-only project:
```hs
{ name = "my-tests"
, packages = ../packages.dhall
, dependencies = [ "console", "effect", "prelude" ]
, sources = [ "test/**/*.purs" ]
}
```
