### ISSUE TITLE
7.6.0 does not build

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#176]
no binaries: https://github.com/spacchetti/spago/releases/tag/0.7.6.0

build: https://travis-ci.com/spacchetti/spago/builds/109837292

**Comment by f-f** [comment]
Yeah I realized too late. I'll amend `0.7.6` and make a new release

**Comment by f-f** [comment]
Released 0.7.7.0: https://github.com/spacchetti/spago/releases/tag/0.7.7.0

**Comment by justinwoo** [comment]
coolz
