### ISSUE TITLE
spago init force shouldn't overwrite existing packages.dhall

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#179]
when someone has a psc-package local setup with spago

```
psc-package.json
packages.dhall
```

then running spago init force should not overwrite packages.dhall.

there's also some kind of performance problem with how the spago.init file is generated? it takes almost 30s to generate from a list of maybe 40 deps: https://github.com/justinwoo/vidtracker/commit/c62acdd015f908b00256d2d21b6ccdfe4985d0fe. this might be "fixed" just by trying a newer dhall version dep

**Comment by f-f** [comment]
@justinwoo I was thinking of removing the `--force` flag entirely. The reason is that it might not be possible to have it cover all usecases, so it's better if the user deals with the edge cases directly instead of doing the wrong thing. What do you think?

Re performance issues: I suspected there were issues with the psc-package migration, I'll profile it with your project file and see if we can improve it

**Comment by f-f** [comment]
@justinwoo update on the performance problem: I can reproduce it only once, all subsequent executions are very fast. So I'm going to guess that the 30s are caused by the resolution and caching of a new package set, so we cannot do much about it

Timing information on `vidtracker` with "hot cache":
```
 $ spago init | tdiff
(1.57 s) Found a "psc-package.json" file, migrating to a new Spago config..
(125.32 µs) Done. Updating the "spago.dhall" file..
(29.20 µs) Found existing directory "src", skipping copy of sample sources
(19.23 µs) Found existing directory "test", skipping copy of sample sources
(18.16 µs) Found existing file ".gitignore", not overwriting it
(201.44 µs) Set up a local Spago project.
(28.47 µs) Try running `spago build`
```

**Comment by f-f** [comment]
And update on `spago init`: I think that if we keep the `--force` then it's ok if it overwrites everything, I think the bug here is that `spago init` should skip the `packages.dhall` if it's already there and just create the `spago.dhall`
