### ISSUE TITLE
Document how to add dev-only dependencies

### ISSUE THREAD

**Issue by thurn** [spacchetti/spago#191]
Trying to use spago for the first time, it is not apparent what the equivalent of `bower install --save-dev` is, if I want to add something like `purescript-spec` as a dependency for my unit tests.

Looking at some random examples on Github, it seems like people mostly just include these along with their regular dependencies? Perhaps that is the correct approach, but either way this feels like it merits a mention in the documentation since it's a core Bower feature.

**Comment by thurn** [comment]
Oh, I guess this is a Duplicate of #178

**Comment by f-f** [comment]
Yes! This is also going to be documented in https://github.com/spacchetti/spago/pull/201
