### ISSUE TITLE
spago installed via npm does not seem to fully install

### ISSUE THREAD

**Issue by bbarker** [spacchetti/spago#192]
```
brandon@c9460f72c9e4:/wd$ type -a spago
spago is /usr/local/bin/spago
brandon@c9460f72c9e4:/wd$ cat /usr/local/bin/spago
#!/usr/bin/env bash
set -e

echo "This is a stub that will be replaced on install. \
It is needed to workaround https://github.com/yarnpkg/yarn/issues/3421"
```

I have a container for this that reproduces the issue: 305e449d39b9a146f5bfca1f335a80cd2c2bebe0 at https://github.com/bbarker/purescript-hodgepodge, or just use master's HEAD for now.

To run the container, use `psc.sh` in the repo, or a modified version that has fewer mounts, though I'm not sure what the behavior will be (should be mostly fine though). To build the container, you can run `build.socker.sh`.

**Comment by f-f** [comment]
Thanks for the report @bbarker! 

Some notes:
1. I'd recommend downloading `spago` in the same way you're downloading the `purs` and `psc-package` binaries in the container, as that's much more reliable than npm
2. I'm able to reproduce just trying to install `spago` on a bare `node` image, I'll investigate more on this:

```bash
$ docker-bash node:12
root@71c1f9e95b14:/# npm install -g spago

> spago@0.7.7 preinstall /usr/local/lib/node_modules/spago
> node ./install.js

/usr/local/bin/spago -> /usr/local/lib/node_modules/spago/spago.exe
+ spago@0.7.7
added 29 packages from 19 contributors in 4.809s
root@71c1f9e95b14:/# spago -v
This is a stub that will be replaced on install. It is needed to workaround https://github.com/yarnpkg/yarn/issues/3421
root@71c1f9e95b14:/#
```

**Comment by f-f** [comment]
Found it. TL;DR: you need to use `--unsafe-perm` as an npm option if you want to install packages as root and have them to work, or just set a user in your Dockerfile. See [this medium post](https://medium.com/@aguidrevitch/when-installation-of-global-package-using-npm-inside-docker-fails-b551b5dda389) or [this StackOverflow question](https://stackoverflow.com/questions/46111738/how-to-install-global-module-in-docker) for more info.

So running this command in the container works correctly: `npm install -g --unsafe-perm spago`

I feel this "installing npm packages as root" might be a common problem, so we should definitely add to the FAQ something along the lines of "**DON'T RUN NPM AS ROOT**"

**Comment by JordanMartinez** [comment]
I don't know the full context of this issue (so my apologies if this isn't
helpful), but isn't this a symptom of not configuring the npm prefix to a
directory that doesn't require root privileges? Otherwise, one has to run
node with root privileges to get anything to work.

>

**Comment by f-f** [comment]
@JordanMartinez what happens here is that Docker by default runs all commands as root (unless you specify otherwise), combined with the fact that npm installs binaries as `nobody` when root. See the links in my previous comment, or this issue: https://github.com/npm/npm/issues/3849

The result is that installing spago with npm running as root will never work, unless `--unsafe-perm` is specified

**Comment by JordanMartinez** [comment]
@f-f Gotcha. Thanks for clarifying that for me.

**Comment by f-f** [comment]
@JordanMartinez you're welcome! 🙂
