### ISSUE TITLE
Issue with calling purescript functions from javascript

### ISSUE THREAD

**Issue by bbarker** [spacchetti/spago#193]
This commit demonstrates how I tried and failed to go from using a main-based function to using function calls from within `<script>` elements: https://github.com/bbarker/purescript-concur-starter/commit/98a28a498b44c3dd7a359c6bd550c6811ce6d510

Not necessarily more concise, but for completeness, the index.html and index.js are now:

```html
<!doctype>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Hello Concur!</title>
  <script type="application/javascript" src="index.js"></script>
</head>
<body>
  <div id="root"></div>
  <script type="application/javascript" src="index.js">
    NotMain.notMain();
  </script>
</body>
</html>

```

```javascript
require("./output/NotMain");                  // builds but runtime error
// require("NotMain");                        // doesn't build
// import NotMain from "./output/NotMain";    // builds but runtime error
```

Granted, this was with parcel bundler - the Spago Readme sort of implied that i might need to use something other than`spago bundle-module` if using js libs (this uses React) - please correct me if I'm wrong.

CC'ing @ajnsit, the author of the original code, as he might have some insight, particularly on the parcel-bundler choice.

## Error in browser

```
SyntaxError: An invalid or illegal string was specified hmr-runtime.js:29:2
    parcelRequire<["node_modules/parcel-bundler/src/builtins/hmr-runtime.js"]< hmr-runtime.js:29
    newRequire purescript-concur-starter.e31bb0bc.js:47
    parcelRequire purescript-concur-starter.e31bb0bc.js:81
    <anonymous> purescript-concur-starter.e31bb0bc.js:8
```

## To reproduce

```
git clone https://github.com/bbarker/purescript-concur-starter.git
cd purescript-concur-starter
git checkout function_call_from_js
npm run start
# now browse to the dist/index.html page in your browser
```

**Comment by bbarker** [comment]
I now have also tried:
```
 "start2": "spago bundle app --main NotMain --to dist/index.js && cp index.html dist/",
```
alternatively with `bundle module` instead of `bundle app`.

Int this case I get an error from the browser: `ReferenceError: require is not defined[Learn More] index.js:3503:7` (as might be expected for the `bundle module` case based on the documentations).

**Comment by bbarker** [comment]
Using  parcel, and index.js = `import * as NotMain from "./output/NotMain";`, if we pass `--no-hmr` to `parcel`, then the error goes away. But, thee app function calls to `notMain()`, `notMain`, `NotMain.notMain()`, `NotMain.notMain` still appears to have no effect.

In the generated output:

```javascript
var notMain = Concur_React_Run.runWidgetInDom("root")(hello);
module.exports = {
  hello: hello,
  notMain: notMain
};


var NotMain = _interopRequireWildcard(require("./output/NotMain"));

```

Giving the sense that `notMain` may be evaluated upon load, though hard to tell from the generated JS output

In any case, rearranging like this did not help:

```html
  <div id="root"></div>
  <script type="application/javascript" src="index.js"></script>
  <script type="application/javascript">
   NotMain.notMain();
  </script>
```

**Comment by bbarker** [comment]
Workaround (as pointed out by tex on Slack), is to have the following `index.js`

```javascript
var NotMain = require("./output/NotMain"); 
window.NotMain = NotMain;
```

**Comment by f-f** [comment]
@bbarker it sounds like this is a parcel quirk, but maybe we should still document it as a "gotcha" in here?

**Comment by bbarker** [comment]
I think it is definitely worth a mention in docs somewhere. Maybe there
should be a docs repo/gist on Purescript and Parcel and link to that?

**Comment by f-f** [comment]
@bbarker 👍

We could point to the [TodoMVC with react-basic and spago](https://github.com/f-f/purescript-react-basic-todomvc) since it's already linked somewhere else in the docs
