### ISSUE TITLE
Watch should also watch FFI JS files

### ISSUE THREAD

**Issue by Sir4ur0n** [spacchetti/spago#205]
As discussed with @f-f currently Spago watch mode doesn't watch FFI files.

```
/  SomeComponent.purs
|- SomeComponent.js
```
When modifying `SomeComponent.js`, Spago doesn't rebuild the application.

I think this would make sense if it did.

**Comment by f-f** [comment]
Yeah the `.js` files are excluded from the watch currently for ease of implementation: when [passing in the globs to watch](https://github.com/spacchetti/spago/blob/118f817b638fd96f1d3711de000bea9c1d954915/app/Spago/Build.hs#L77) we use the same ones that are used in the normal build, which [only include `.purs` files](https://github.com/spacchetti/spago/blob/118f817b638fd96f1d3711de000bea9c1d954915/app/Spago/Packages.hs#L95).
I think we could add this

I won't have time to look at this myself anytime soon, so I'll leave a guideline for the fix in case someone wants to look at it: I think we could add another function called e.g. `getJsGlobs` that would return the same globs as `getGlobs` but with a `.js` extension. Then they should be passed to the watcher in `Spago.Build.build`.
Note: the problem of implementing this is that if the generated files end up being included in the globs then the watcher will start to trigger itself continuously.

**Comment by stkb** [comment]
(@rnons sorry now that you've done the work but) would it not be simpler just to watch all files in the given source directories? I can't think that there would be too many changes there anyway.

It would simplify the code and also future-proof it for other backends.

**Comment by rnons** [comment]
I'm not sure if we want to watch `src/**/*`, there can be many files in `src` not related to purescript. Even if we watch `src/**/*`, we still need to pass different globs to build and watch. Passing `src/**/*.js` to purs will throw parse errors.

In my PR, I applied `Text.replace ".purs" ".js"` to each entry in the `sources` config, which is a hack. What I really want is a new config called `watchGlobs` / `watchPatterns` or something.
