### ISSUE TITLE
Add option to clear the screen to spago build

### ISSUE THREAD

**Issue by masaeedu** [spacchetti/spago#209]
`spago build -w` is pretty handy as a lightweight equivalent to `ghcid` in Haskell. It'd be nice if we could also get it to clear the screen when it rebuilt, so that we can keep it open in a pane alongside the code and clear up the errors as we go.

**Comment by f-f** [comment]
@masaeedu great idea!

I won't be able to pick this up so I'll mark it as up for grabs. The clearing of the screen should happen [somewhere in this block](https://github.com/spacchetti/spago/blob/c567fcb1cac27774965fc8189e6a4f34127540bf/app/Spago/Watch.hs#L120-L132), paying extra attention that we don't clear the help block (that shows up when e.g. typing `help`)

**Comment by miangraham** [comment]
I'm poking at this for a first issue. Clearing is working, just need to add the new build config. Looks straightforward. Will swing by in person tomorrow to compare notes. Shout if I'm stepping on anybody's toes.
