### ISSUE TITLE
Install fails: `openBinaryFile: inappropriate type (is a directory)`

### ISSUE THREAD

**Issue by JordanMartinez** [spacchetti/spago#220]
### Environment

```
$ purs --version
0.12.5
$ spago version
0.8.1.0
$ npm --version
6.9.0
$ node --version
v10.15.3
```

Is this a bug in latest Spago release?

```bash
$ spago init
Initializing a sample project or migrating an existing one..
Set up a local Spago project.
Try running `spago build`

$ spago build
Installing 4 dependencies.
Searching for packages cache metadata..
Recent packages cache metadata found, using it..
Installing and globally caching "psci-support"
Installing and globally caching "console"
spago: Installation failed.

Error:

/tmp/console-v4.2.0-e975759a2f6f20dc/download/purescript-console-4.2.0: openBinaryFile: inappropriate type (is a directory)
```

### Other Notes

This seems to fail at the first alphabetical directory it encounters. If I install a package starting with `b`, it errors with that package first:
```bash
$ spago install bifunctors
Done. Updating the "spago.dhall" file..
Installing 6 dependencies.
Searching for packages cache metadata..
Recent packages cache metadata found, using it..
Installing and globally caching "console"
Installing and globally caching "bifunctors"
Installing and globally caching "effect"
spago: Installation failed.

Error:

/tmp/bifunctors-v4.0.0-c542bebcb6da4107/download/purescript-bifunctors-4.0.0: openBinaryFile: inappropriate type (is a directory)
```
Immediately after this, I install something starting with an `a`
```bash
$ spago install aff
Done. Updating the "spago.dhall" file..
Installing 41 dependencies.
Searching for packages cache metadata..
Recent packages cache metadata found, using it..
Installing and globally caching "console"
Installing and globally caching "effect"
Installing and globally caching "bifunctors"
Installing and globally caching "contravariant"
Installing and globally caching "arrays"
Installing and globally caching "datetime"
Installing and globally caching "const"
Installing and globally caching "distributive"
Installing and globally caching "control"
Installing and globally caching "enums"
Installing and globally caching "either"
Installing and globally caching "aff"
spago: Installation failed.

Error:

/tmp/aff-v5.1.1-0910dd925c1c07e6/download/purescript-aff-5.1.1: openBinaryFile: inappropriate type (is a directory)
```
Immediately after this, I install a package whose name's first letter appears later in the alphabet. Notice how `aff` is still the issue.
```bash
$ spago install halogen
Done. Updating the "spago.dhall" file..
Installing 73 dependencies.
Searching for packages cache metadata..
Recent packages cache metadata found, using it..
Installing and globally caching "contravariant"
Installing and globally caching "const"
Installing and globally caching "console"
Installing and globally caching "coroutines"
Installing and globally caching "aff"
Installing and globally caching "avar"
ERROR: Nothing
Installing "unsafe-reference"
spago: Installation failed.

Error:

/tmp/aff-v5.1.1-fc1cdd9018241dc1/download/purescript-aff-5.1.1: openBinaryFile: inappropriate type (is a directory)
```

**Comment by f-f** [comment]
@JordanMartinez yep, it looks like a bug in the handling of the temp directories (which is new in the latest release). Let's see if we can debug this quickly so we get out a bugfix release asap

Which OS are you on?

**Comment by JordanMartinez** [comment]
Linux mint 19.1
I believe.

**Comment by f-f** [comment]
Wonderful thanks! I'll try to replicate and isolate the problem (since we don't get any source line reference, I'll also look at how to enable those in errors)

In the meanwhile you should be able to get around the problem by skipping the global cache with `--global-cache=skip`

**Comment by JordanMartinez** [comment]
Looks like that option still doesn't work

**Comment by f-f** [comment]
@JordanMartinez what's the new output you get?

**Comment by JordanMartinez** [comment]
```bash
$ spago install --global-cache=skip
Installing 4 dependencies.
Installing "psci-support"
Installing "console"
Installing "prelude"
Installing "effect"
spago: Installation failed.

Error:

/tmp/console-v4.2.0-0aceed02d689f001/download: openBinaryFile: inappropriate type (is a directory)
```

**Comment by f-f** [comment]
Wow, this is interesting. Some updates:
- I am unable to reproduce on `macOS Sierra`, `NixOS 19.03` and `Ubuntu 19.04`, i.e. `spago build` works as intended on all of them
- By the output you get it seems like the global cache is not a problem, but rather it's localized in the new download strategy with temp dirs. By the looks of it I think something is wrong with the `mv` that happens [here (with global cache)](https://github.com/spacchetti/spago/blob/3641479a9c72f5fb23f0e7cf0f7fd53b4e54349f/app/Spago/FetchPackage.hs#L114) or [here (without)](https://github.com/spacchetti/spago/blob/3641479a9c72f5fb23f0e7cf0f7fd53b4e54349f/app/Spago/FetchPackage.hs#L130)

Next I'll try to grab a docker image for the latest Mint and see if I manage to reproduce there..

**Comment by JordanMartinez** [comment]
I think I'll have to build this project on my own machine and troubleshoot from there. If you've gotten it to work on other things, then I'm not sure why it isn't working on mine...

**Comment by f-f** [comment]
@JordanMartinez that would be great!

I think it would be already of great help to sprinkle some `echo`s around the piece of code above (especially inside the `cacheableCallback` and `nonCacheableCallback` blocks) so we can see exactly where it breaks (i.e. I have no idea which underlying library call is using the `openBinaryFile`)

**Comment by JordanMartinez** [comment]
Using `retry.sh` to help make this feedback loop faster...
```bash
##!/usr/bin/env bash
# I'm running this in my cloned version of `spago`, at its root directory

# Remove global cache directory
rm -r ~/.cache/spago/

rm -rf bugSpago/
mkdir bugSpago
cd bugSpago/

./../.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/spago/spago init
./../.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/spago/spago install $1

```
This is the output.

Global cache:
```bash
$ ./retry.sh 
rm: cannot remove '/home/jordan/.cache/spago/': No such file or directory
Initializing a sample project or migrating an existing one..
Set up a local Spago project.
Try running `spago build`
Installing 4 dependencies.
Searching for packages cache metadata..
ERROR: /home/jordan/.cache/spago/metadataV1.json: getModificationTime:getFileStatus: does not exist (No such file or directory)
Unable to find packages cache metadata, downloading from GitHub..
Installing and globally caching "effect"

Moving directory: resultDir -> packageGlobalCacheDir:
resultDir path: '/tmp/effect-v2.0.1-aa7545e3d5cce3b2/download/purescript-effect-2.0.1'
packageGlobalCacheDir path: '/home/jordan/.cache/spago/effect/v2.0.1'
Installing and globally caching "psci-support"
Installing and globally caching "console"

Moving directory: resultDir -> packageGlobalCacheDir:
resultDir path: '/tmp/psci-support-v4.0.0-68128a44944b2e16/download/purescript-psci-support-4.0.0'
packageGlobalCacheDir path: '/home/jordan/.cache/spago/psci-support/v4.0.0'

Moving directory: resultDir -> packageGlobalCacheDir:
resultDir path: '/tmp/console-v4.2.0-31b893685dbbd1ba/download/purescript-console-4.2.0'
packageGlobalCacheDir path: '/home/jordan/.cache/spago/console/v4.2.0'
spago: Installation failed.

Error:

/tmp/console-v4.2.0-31b893685dbbd1ba/download/purescript-console-4.2.0: openBinaryFile: inappropriate type (is a directory)
```

Skipping global cache:
```bash
$ ./retry.sh --global-cache=skip
Initializing a sample project or migrating an existing one..
Set up a local Spago project.
Try running `spago build`
Installing 4 dependencies.
Installing "console"
Installing "prelude"
Installing "psci-support"
Installing "effect"

NoncacheableCallback
downloadDir path: '/tmp/console-v4.2.0-7ed5c112d18b928c/download'
packageLocalCacheDir path: '/home/jordan/Programming/Git Projects/spago/bugSpago/.spago/console/v4.2.0'
spago: Installation failed.

Error:

/tmp/console-v4.2.0-7ed5c112d18b928c/download: openBinaryFile: inappropriate type (is a directory)
```

This confirms that the issue is with `mv` as there should be a "Moving Directory: source -> destination: **Finished**" part that gets printed after that command succeeds.

**Comment by JordanMartinez** [comment]
Related commands:
- [`mv`](https://hackage.haskell.org/package/turtle-1.5.14/docs/src/Turtle.Prelude.html#mv)
- [`rename`](https://hackage.haskell.org/package/system-fileio-0.3.16.4/docs/src/Filesystem.html#rename)

**Comment by f-f** [comment]
Thanks for looking into this! What are the permissions on your `/tmp` folder?

**Comment by JordanMartinez** [comment]
```bash
$ cd /
$ ls -l -a | grep 'tmp'
drwxrwxrwt  23 root root  4096 May 30 22:18 tmp
```

**Comment by JordanMartinez** [comment]
I think it's pretty clear that the issue occurs due to the `mv` command. The fact that that works fine on Ubuntu 19.04 and Linux Mint 18 makes me wonder whether there is something else going on and this is only the symptom of the real issue.

I'll try running the binary that gets produced via `stack build` on a LiveUSB with Linux Mint 19.1 to confirm that the OS isn't the issue.

**Comment by JordanMartinez** [comment]
Well, the OS seems to be the issue. After doing all that work on a LiveUSB, the problems still appeared.

Steps I took:
- installed `nvm`, `node`, and `purescript`
- git cloned this repo
- inserted my echo statements
- installed `stack`
- ran `stack test` to produce the binary, which errored
- came across a variant of #104 and fixed it with that solution
- ran `stack test` successfully
- ran the `retry.sh` file
- same errors as before were outputted

**Comment by vanceism7** [comment]
Just to chime in here, I'm also experiencing this error on Manjaro (ArchLinux)

**Comment by f-f** [comment]
@vanceism7 great to know! I'll test next with an [Arch image](https://hub.docker.com/r/archlinux/base/)

@JordanMartinez just a small note: `stack test` runs the globally installed executable, so there should be a `stack install` somewhere in your command list. If you did it before `stack test` then it's extra weird because the test pass? (they do install and build things, etc)

**Comment by uzantnomo** [comment]
@f-f I experience the same problem on Manjaro.

However I'm unable to reproduce the error in docker arch image. Here is the [gist with Dockerfile](https://gist.github.com/uzantnomo/4a6b2b332aae13347797ae4987791bbb) (I tried to init an build spago project both as root and as a normal user with no failures).

**Comment by f-f** [comment]
@uzantnomo thanks for testing this!

I'll recap where it works and where it doesn't.
It works in:
- `macOS Sierra`
- `Ubuntu 18.04`
- `Ubuntu 19.04`
- `NixOS 19.03`
- `Mint 18 (docker image)`
- `Arch (docker image)`

It doesn't in:
- `Mint 19`
- `Manjaro`

**Comment by f-f** [comment]
I'm now wondering if taking the temp folder creation off of the global `tmp` folder would work. I'll push some commits to a branch and ask you to test that

**Comment by JordanMartinez** [comment]
> just a small note: stack test runs the globally installed executable, so there should be a stack install somewhere in your command list. If you did it before stack test then it's extra weird because the test pass? (they do install and build things, etc)

@f-f I learned via some blog post or something to not use `stack install` precisely because it installs the binary globally (the name is usually interpreted as 'install the dependencies' rather than what it actually does: 'install the binary globally') and instead to use `stack build`. I didn't need to do that on the LiveUSB, but habits and all... 
`stack test` seems to run `stack build` before it runs the tests. Either way, I know that the binary I used works because `stack test` doesn't print the echo statements to the console, but does build a binary somewhere in the `.stack-work` directory that does print those statements when used. So, I just used that binary.

Also note: `spago 0.8.0.0` worked fine for me.

> I'm now wondering if taking the temp folder creation off of the global tmp folder would work. I'll push some commits to a branch and ask you to test that

Sounds good! I thought I'd have more time today, but it doens't look like it. So, I won't be able to try that out until Monday or so.

**Comment by f-f** [comment]
> `stack test` seems to run `stack build` before it runs the tests. Either way, I know that the binary I used works because `stack test` doesn't print the echo statements to the console, but does build a binary somewhere in the `.stack-work` directory that does print those statements when used. So, I just used that binary.

What I meant is that running `stack test` exercises the same code paths that we're looking at here: so how is it possible that the tests pass but then running the binary by hand doesn't work? The tests also install and build things..

**Comment by JordanMartinez** [comment]
Oh, they don't pass. stack test fails but it didn't help me determine which
paths were actually being used. For example, I wasn't sure whether "/temp"
referred to a temporary folder in the project folder or the "/temp" folder
that's in the "/" directory

**Comment by f-f** [comment]
It was easier than expected to move the tempdir to the local repo, here's the branch: https://github.com/spacchetti/spago/tree/try-to-fix-tempdirs2

**Comment by srghma** [comment]
I'm on nixos, will try the branch

**Comment by vanceism7** [comment]
Just tried the `try-to-fix-tempdirs2` branch and that seems to have fixed the problem on Manjaro :tada:

**Comment by srghma** [comment]
confirm

**Comment by f-f** [comment]
Nice! I opened #243 from that branch, but I'll wait for @JordanMartinez to test it before merging

**Comment by JordanMartinez** [comment]
@f-f The branch works!

**Comment by f-f** [comment]
This is amazing news 😄 🎉 

Then I'll merge #243 and cut a new release. Thanks everyone for the help!

**Comment by JordanMartinez** [comment]
Thanks!
