### ISSUE TITLE
Report all missing packages together

### ISSUE THREAD

**Issue by hdgarrood** [spacchetti/spago#223]
If there are a number of packages which are listed as dependencies in my `spago.dhall` but which do not exist in my package set, `spago` reports these one by one. For example:

```
$ spago build
spago: Package `fixed-precision` does not exist in package set
# Add `fixed-precision` ...
$ spago build
spago: Package `reflection` does not exist in package set
# Add `reflection` ...
$ spago build
...
```

I think it would be better to report all missing packages together, if possible. Of course it won't always be possible to do so: suppose package A depends on package B, and package B depends on C, and I add A as an addition without adding B or C; in this case we might not know that C is missing until we add B.

For a minimal reproduction example, run `spago init` in an empty directory, and modify the `spago.dhall` file as follows:
```
{-
Welcome to a Spago project!
You can edit this file as you like.
-}
{ name =
    "my-project"
, dependencies =
    [ "effect", "console", "psci-support", "blah", "what" ]
, packages =
    ./packages.dhall
}
```
and then run `spago build`. The error you receive is:
```
spago: Package `blah` does not exist in package set
```
However, it would be nicer to get something like
```
spago: The following packages do not exist in your package set:
  - blah
  - what
```

**Comment by f-f** [comment]
Nice 😄 

Agreed that this is not nice indeed. The fix should be quite straightforward: on line 101 instead of calling `die` we should accumulate the missing packages:
https://github.com/spacchetti/spago/blob/05815ce7a7f2cbf0767a421e2ebf6b028385e69d/app/Spago/Packages.hs#L88-L104
