### ISSUE TITLE
New name proposal

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#23]
As we discussed some time ago with @justinwoo, the name of this repo/program has a bit of a name clash with the [spacchetti package set repo](https://github.com/justinwoo/spacchetti), and this is super confusing.

So I'd like to propose a new name for this repo and tool: **spago**
(IPA: */ˈspaɡo/*)

Why?
- It means "twine" in Italian, and it would symbolize the new role of this tool (well at least after #21), to "tie everything together"
- It is different than `spacchetti`
- It kind of reminds of it at the same time (they have the same root)
- It is actually shorter to type at the command line, but unique enough

Sample image to visualize it:
<img alt="spago" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Bindfaden.jpg/1200px-Bindfaden.jpg" width="50%"/>

**Comment by justinwoo** [comment]
@nwolverson what do you think of this name change?

**Comment by nwolverson** [comment]
What I'm the arbitrer of taste now? It's a name, I can probably find it by tab completing => ok!
