### ISSUE TITLE
Hashes not generated when running psc-package-insdhall

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#240]
Compare with `spago install` with `psc-package-insdhall` for remote imports

**Comment by f-f** [comment]
If I understood correctly what you mean, the fix should just be to add `ensureFrozen` to the [PscPackage module](https://github.com/spacchetti/spago/blob/master/app/Spago/PscPackage.hs). This is where it's done for `spago install`:
https://github.com/spacchetti/spago/blob/c3e27219f367810d7ac771c5c48ab8e5ac209824/app/Spago/Config.hs#L79

**Comment by justinwoo** [comment]
sounds good
