### ISSUE TITLE
Usage with `purescript-psa`

### ISSUE THREAD

**Issue by joneshf** [spacchetti/spago#252]
As mentioned on slack, we'd like to be able to use [`psa`][]. [`psa`][] tends to be a direct swap for `purs`, so that's a common workflow when writing commands by hand. There's no explicit requirement that we have to set the binary name `purs` to something else, but that might be the simpler/more robust way to go about it.

Is this a thing `spago` can support? The implementation of that support I have no strong feelings about at the moment.

[`psa`]: https://github.com/natefaubion/purescript-psa

**Comment by f-f** [comment]
@joneshf yes I'd say spago could easily support this, especially if `psa` is CLI-compatible with `purs`

The most straightforward way to implement it could probably be to add a `--purs-binary` flag to customize the calls to `purs`, that would set a `GlobalOption` (defaulting to `purs`)
