### ISSUE TITLE
spago run -- needs to pass through args to node, or have some mechanism to do so

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#267]
Main.js

```js
exports.argv = process.argv;
```

Main.purs

```purs
module Main where

import Prelude

import Effect (Effect)
import Effect.Aff as Aff
import Effect.Class.Console (logShow)

foreign import argv :: Array String

main :: Effect Unit
main = Aff.launchAff_ do
  logShow argv
```

actual:

```
$ spago run -- afwaefwaefo
Installation complete.
purs compile: No files found using pattern: afwaefwaefo
Build succeeded.
["my/bin/node"]
```

expected:

```
$ node -e "require('./output/Main').main()" 12313 owijewejf
["my/bin/node","12313","owijewejf"]
```

**Comment by f-f** [comment]
There is a small issue here, and it's that everything that goes after `--` gets passed to `purs` in all commands that might build (`build`, `bundle-*`, `run`, etc), so I think we should keep it like that everywhere for consistency. 

So how about adding a `--node-args` flag to the `test` and `run` commands?

**Comment by miangraham** [comment]
Got some open hacking time and just finished adding other new arg. I can try a first pass at this today.
