### ISSUE TITLE
Build without installation

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#269]
Is there something I don't know about already?

Or do I need to be able to skip this?

https://github.com/spacchetti/spago/blob/043a2ad4df78b9920d5debf8c2980f5f987c5b37/src/Spago/Build.hs#L71

**Comment by f-f** [comment]
We can add a flag like `NoInstall` like the `NoBuild` that we already have in the bundle (e.g. see [here](https://github.com/spacchetti/spago/blob/99ae8e837b88fe3fca433a83d582d3e0ebe98156/src/Spago/Build.hs#L136))
