### ISSUE TITLE
command to print spago.dhall sources as JSON

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#276]
given

```dhall
{ sources =
    [ "src/**/*.purs", "test/**/*.purs" ]
, name = -- ...
}
```

```json
 [ "src/**/*.purs", "test/**/*.purs" ]
```

(but this also needs to normalize the expression first)

**Comment by f-f** [comment]
@justinwoo could you depend on `dhall-to-json`? Then you could do

```dhall
dhall-to-json <<< "(./spago.dhall).sources"
```

**Comment by justinwoo** [comment]
to be confirmed

**Comment by justinwoo** [comment]
i had to use a mess of writing to stdin on a child process as a result, since there's no --file arg in dhall-to-json, and using --file just complains about not being able to resolve

**Comment by justinwoo** [comment]
maybe less important with https://github.com/spacchetti/spago/pull/274

**Comment by f-f** [comment]
@justinwoo the `--file` issue is fixed in master, fix went in with https://github.com/dhall-lang/dhall-haskell/pull/1004, so it should work properly with the upcoming release

**Comment by f-f** [comment]
@justinwoo would the solution proposed in #287 work for you?

**Comment by justinwoo** [comment]
maybe it's okay, you can close this issue
