### ISSUE TITLE
Add `--local` flag to `spago init` to replace imported package set with the normalized form

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#306]
Everyone and their dog knows that importing packages.dhall right now is slower than a scooter in quicksand. However, it would be nice if only one victim had to pay the cost of running that on their computer for a given project.

"Before"

```dhall
let mkPackage =
      https://raw.githubusercontent.com/purescript/package-sets/psc-0.13.0-20190611/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57

let upstream =
      https://raw.githubusercontent.com/purescript/package-sets/psc-0.13.0-20190611/src/packages.dhall sha256:2631fe1dce429e5f27324e59cc834e8e8832a5d533423952105c7446320a3648

in      upstream
```

"After"

```dhall
let mkPackage =  -- whatever goes here

let upstream =
      { -- ......
      }

in      upstream
```

**Comment by f-f** [comment]
@justinwoo I think `dhall <<< "./packages.dhall" > packages-cached.dhall` would do the trick unless I'm missing something

**Comment by justinwoo** [comment]
I would like to at the very least preserve "let upstream = {}" because that lets me save some effort by only appending `// { override = upstream.override // { version = 123123123123`

**Comment by f-f** [comment]
I wouldn't like Spago to have logic to do this, since:
- it's not part of "normal operating mode" (i.e. it's a custom thing you want to do with your projects but not a thing I'd normally suggest)
- it can be done with 10 lines of bash/perl/python/sed to customize the result to your liking (this is the same rationale as with #150)

What we can do is to expose a `dhall` interpreter from Spago, so you don't have to depend on the `dhall` executable if you don't want to

**Comment by f-f** [comment]
Another interesting solution for this could be to have a flag for `spago init` (e.g. `--local`) that would initialize a project that has the whole package set already in `packages.dhall` instead of importing it (and this can have that shape that you want)

@justinwoo would this work?

**Comment by justinwoo** [comment]
right, that would probably be fine

**Comment by f-f** [comment]
Awesome, I'll rename the issue to track this then!

**Comment by f-f** [comment]
I'll close this as we agreed with @justinwoo that we'll instead start publishing a rendered version of `packages.dhall` as an artifact on every release of `purescript/package-sets`
