### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#31]
There should be some tests so that we have some kind of assurance that we don't break stuff.

Anything is good to start, even just a bash script that installs the binary, runs some commands and checks that the return codes are all right.
This should prevent simple breakage, like what happened when https://github.com/justinwoo/spacchetti-cli/commit/4e9c20e93d92b18168678dd28a070e901adc3428 lead to #29

**Comment by justinwoo** [comment]
These tests should probably also take into account the difference between Psc-Package projects using local-setup, insdhall and Spacchetti projects using whatever else

**Comment by f-f** [comment]
Yeah, probably best to change the names of the psc-package-related commands, so like `spacchetti insdhall` → `spacchetti psc-package-install` and `spacchetti local-setup` → `spacchetti psc-package-local-setup`

**Comment by justinwoo** [comment]
`psc-package-insdhall`, it's a big selling point for this tool

**Comment by justinwoo** [comment]
It also needs some deprecation warnings since many of my other projects will break
