### ISSUE TITLE
Error: was not able to get a directory for the global cache (Windows)

### ISSUE THREAD

**Issue by sharno** [spacchetti/spago#312]
On a Windows machine, I installed spago using npm

```
> npm -g i spago
> spago init
> spago install react-basic
```

I get this error with `spago install` or `spago build`
```
Error: was not able to get a directory for the global cache. Set either `HOME` or `XDG_CACHE_HOME`
spago.exe: user error (mzero)
```

**Comment by f-f** [comment]
Hi @sharno! This is a normal error condition, and in fact the error message is telling you that you should define either the `HOME` or the `XDG_CACHE_HOME` environment variable, and point it to a path where Spago can put its global cache

If this makes sense, how can we make this error message clearer?

In any case you should be able to disable the global cache with `--no-global-cache`

**Comment by sharno** [comment]
Hi @f-f , thanks for your reply

I think on Windows the environment variable is called `HomePath` instead of just `HOME`. Which points generally to `\Users\{username}` where I find most of the tools' cache folders like `.sbt` or `.stack`

http://environmentvariables.org/HomePath

Otherwise maybe the error should specify explicitly that `HOME` or `XDG_CACHE_HOME` or `HomePath` (if added) are environment variables.

**Comment by f-f** [comment]
@sharno thanks! Fix up in #314 🙂

**Comment by sharno** [comment]
@f-f  Thanks a lot for the quick fix :)

Just one more thing, everything worked fine after I added the environment variable. But when I tried without it but with `--global-cache=skip` or `--global-cache skip` it still throws the same error. Thought I'd mention in case if it's a different bug?

**Comment by f-f** [comment]
@sharno you're welcome! 🙂 

> Thought I'd mention in case if it's a different bug?
Yeah it's a known problem. I looked into disabling the whole logic for global cache (which is probably the right thing to do) if this failed, but at this point there are too many code changes in flight that touch nearby code, so what I did in #314 was to always make this operation succeed, so we shouldn't encounter this error ever again :)
