### ISSUE TITLE
Build messages with spago run should go to stderr

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#316]
So I can do `spago run > my-output-only-pls.txt`

related to #256

**Comment by f-f** [comment]
@justinwoo since we just let the output of the compiler through this is more related to https://github.com/purescript/purescript/issues/3672 right?

Or should we just pour all the output from the compiler to stderr?

**Comment by justinwoo** [comment]
I would like that too, redirecting all of the compiler output to stderr

**Comment by f-f** [comment]
@justinwoo oh right, I just realised that you'd like _all_ the output from spago to go to `stderr`

**Comment by f-f** [comment]
Closing this as duplicated of #256, as I reported all the relevant things from here in https://github.com/spacchetti/spago/issues/256#issuecomment-513116049
