### ISSUE TITLE
Running `spago init` twice overwrites `packages.dhall`

### ISSUE THREAD

**Issue by menelaos** [spacchetti/spago#318]
Steps to reproduce:
1. `spago init`
2. Modify `packages.dhall`
3. `spago init`

The second `spago init` overwrites the modified `packages.dhall` file.
It looks like the bug was introduced in [this PR](https://github.com/spacchetti/spago/pull/180/files) (changing `die` to `echo` in `makePackageSetFile`).

**Comment by f-f** [comment]
Fix up in #321
