### ISSUE TITLE
Remove mkPackage from template

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#320]
mkPackage, the little function that never quite was :cry: :trumpet: (<-- this plays Taps, or auld lang syne, depending on your religion)

https://github.com/purescript/package-sets/pull/399

**Comment by f-f** [comment]
While I have no solution for the emoji rebus, I think we should also output a warning for folks that still have it in their `packages.dhall` (i.e. either traverse the AST or just grep searching for "mkPackage"), so that they can migrate and we can remove it from package-sets when releasing 1.0
