### ISSUE TITLE
Spago run --watch runs(/compiles) twice with vim

### ISSUE THREAD

**Issue by googleson78** [spacchetti/spago#346]
I'm not sure if this is a bug with `spago` or something stemming from my setup (I don't have the same issue with `stack --file-watch` though), so sorry in advance if this is a mistake on my part!

Repro steps:

0. `spago init`
1. `spago run --watch`
2. After the initial run, save `src/Main.purs` (even without modifying it). I use `vim` to do this step.

Expected behaviour:
Files are compiled and run once.

Observed behaviour:
Files are run (and possibly compiled?) twice.

Sample output after a save:
```
File changed, rebuilding: "/home/googleson78/git/spago-watch-double-compile-repro/src/Main.purs"
Compiling Main
Build succeeded.
🍝
Success! Waiting for next file change.
Type help for available commands. Press enter to force a rebuild.
Build succeeded.
🍝
Success! Waiting for next file change.
Type help for available commands. Press enter to force a rebuild.
```
`spago` version is `0.8.5.0`

**Comment by klntsky** [comment]
My neovim does this too. But not `nano`.
I believe this is related: https://vi.stackexchange.com/questions/11629/set-backupcopy-yes-doesnt-still-writes-the-file-twice

**Comment by googleson78** [comment]
Thanks!

Setting `backupcopy=yes` resolves this problem, however I am still left wondering what the difference between `spago` and `stack`s file change detection is.

**Comment by f-f** [comment]
I literally copypasted the implementation from Stack's one, so I'm not sure. I'll take a look

**Comment by f-f** [comment]
@googleson78 which OS are you on?

**Comment by googleson78** [comment]
Linux (Debian testing)

**Comment by f-f** [comment]
@googleson78 could you try the branch from #362?

If that doesn't work you could try tweaking the debounce time [here](https://github.com/spacchetti/spago/pull/362/files#diff-dc77e7cd40666b5c8208568a77cfb050R28)

**Comment by klntsky** [comment]
May it be so that debounce settings do not apply if a file was deleted and re-created, just like Vim does?

**Comment by klntsky** [comment]
I tried building from #362 and I still get all `File changed, triggering a build` messages duplicated when using nvim.

**Comment by f-f** [comment]
> May it be so that debounce settings do not apply if a file was deleted and re-created, just like Vim does?

Oh right, now it makes sense. Then I cannot figure out why it's different from Stack's behaviour

**Comment by klntsky** [comment]
Because the code is different (it diverged)

**Comment by f-f** [comment]
Yeah, though the changes from the original are limited:
- I removed the color stuff
- Generalized from `IO` to `m`
- Wired in our glob stuff
- Removed [this clearing](https://github.com/commercialhaskell/stack/blob/896869ee79d82e3bd9bead30d610ac2bf580cd99/src/Stack/FileWatch.hs#L114) of the dirtiness flag (so you'd get another rebuild if you changed files while the thing was building)

And this last thing might be the reason for this happening, but I still don't understand why

**Comment by googleson78** [comment]
Why did you remove this clearing of a "dirtiness" flag? It seems to me like it would be what saves `stack` (even though it seems to have been added there for a different reason)

**Comment by f-f** [comment]
Update: I tried to apply the last fix I mentioned above, from [here](https://github.com/commercialhaskell/stack/blob/896869ee79d82e3bd9bead30d610ac2bf580cd99/src/Stack/FileWatch.hs#L114), and it didn't help :(
So I'll give up on this, unless someone here has some idea on how to make progress

**Comment by klntsky** [comment]
I think I can give it a try.

**Comment by klntsky** [comment]
I see no way other than re-implementing debouncing.

**Comment by klntsky** [comment]
#371

**Comment by f-f** [comment]
The reason why this didn't happen with Stack but it happened with Spago just dawned on me: Stack watches single files, but we match file modification events against globs instead

**Comment by klntsky** [comment]
So what exactly causes doubled event triggering?

**Comment by f-f** [comment]
@klntsky I did not verify this but I suspect that if you watch the single file you might get less events

**Comment by helinko** [comment]
Nice to see this fixed! Could we get it released soon?

**Comment by f-f** [comment]
@helinko yup, I'm going to cut a release in the next days!
