### ISSUE TITLE
additions doc

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [spacchetti/spago#347]
Beyond [add-a-package-to-the-package-set](https://github.com/spacchetti/spago#add-a-package-to-the-package-set) I don't see the formats to add a package.

Looking for the way to add a remote github repo from a specific branch.

**Comment by f-f** [comment]
There is this note in [the section just above that one](https://github.com/spacchetti/spago#override-a-package-in-the-package-set-with-a-remote-one):

> Note: you can use a "branch", a "tag" or a "commit hash" as a version. Generally it's recommended that you avoid using branches, because if you push new commits to a branch, spago won't pick them up unless you delete the .spago folder.

Would you have any suggestions on how to improve this and make it clearer?

**Comment by f-f** [comment]
Fixed in #398
