### ISSUE TITLE
Ideas: Allow multiple files as an argument to --path/Allow directories as PATHs

### ISSUE THREAD

**Issue by googleson78** [spacchetti/spago#351]
What do you think about the following two:

0. Allow `--path` to accept multiple `PATH`*s, so that globs can easily be used (e.g. `--path src/**/*.purs`) from a shell
1. Allow `PATH` to be a folder which is (perhaps recursively) included for source search

My use case for both of these is that I have a project with multiple source directories (exercises).
Each exercise has its own `Main.purs`, and so I specify what I want via `--path`, so I don't have to create a lot of `spago.dhall`s for each exercise.

**Comment by f-f** [comment]
@googleson78 if you prevent the shell from expanding the globs (e.g. by using single quotes) then it will work, e.g.:
```
$ spago build --path 'src/**/*.purs'
```

**Comment by googleson78** [comment]
Thanks for the quick response!

I guess that is the easiest way. I was just suggesting multiple `PATH`s because iirc `optparse-applicative` easily handles such cases. Feel free to close if neither of those are desirable behaviours for `spago`.

(I can't use `sources` because I have multiple `Main`s. (potentially other clashing names))

**Comment by f-f** [comment]
You're welcome! 🙂 

I'll close this if this solves your usecase, but let's reopen if we find out that this a confusing behaviour
