### ISSUE TITLE
spago docs ignore failed files.

### ISSUE THREAD

**Issue by yihuang** [spacchetti/spago#356]
Currently ``spago docs`` failed on a file, it's probably a ``purs docs`` problem, but I hope spago can ignore the error, and generate docs/tags for other files.

```
$ spago docs -f ctags
Generating documentation for the project. This might take a while..
purs: An internal error occurred during compilation: Failed to decode: output/Data.String.CodeUnits/docs.jsonThe input could not be parsed as JSON
aeson said: Error in $: not enough input
Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:24:3 in purescript-0.13.2-6QPLI9hJaMv7vmLTEn2Yqo:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/Docs/Collect.hs:120:19 in purescript-0.13.2-6QPLI9hJaMv7vmLTEn2Yqo:Language.PureScript.Docs.Collect
spago: Docs generation failed.
```

**Comment by klntsky** [comment]
> I hope spago can ignore the error, and generate docs/tags for other files.

Spago passes compile targets to `purs` as globs, not one-by-one.

Did you try `rm -rf output`? If the problem persists, it's best to report it to https://github.com/purescript/purescript

**Comment by yihuang** [comment]
@klntsky I tried to remove ``output/Data.String.CodeUnits/docs.json``, then it runs ahead, then the error happens again on another module, I do it again for several times, finally it succeeds.

**Comment by yihuang** [comment]
I've opened the issue in purescript(https://github.com/purescript/purescript/issues/3710), so I'm closing this now.
