### ISSUE TITLE
Is there a way to do what --standalone does in pulp?

### ISSUE THREAD

**Issue by cscalfani** [spacchetti/spago#363]
I'd like more control over the execution of main and it seems that I have that with `pulp --standalone <string>`.

**Comment by f-f** [comment]
@cscalfani I believe this was answered in the chat and `spago bundle-module` is what you're searching for?

**Comment by cscalfani** [comment]
Yes. Thanks for writing this here for anyone else who wants to do this.

**Comment by f-f** [comment]
You're welcome 🙂
