### ISSUE TITLE
Check out git repos of dependencies again

### ISSUE THREAD

**Issue by Profpatsch** [spacchetti/spago#365]
A few versions ago, spago cloned the complete git repositories of dependencies.

This was very (very) nice, because “jump to definition” made you land in ”first class” code, with the ability to directly look at history, `git blame` (in the editor), commit changes etc.

If anything, I’d love more support for these kinds of workflows, e.g. where it becomes trivial to create an upstream pull request for changes (and also keep them around in a permanent directory).

**Comment by f-f** [comment]
@Profpatsch this switch happened with the introduction of global cache, where we started fetching tarballs from github if possible. We could have git repos in the global cache, but that would be super slow.

You can totally opt-out of the global cache if you wish so, by passing `--global-cache=skip`

Would that work for you?

**Comment by Profpatsch** [comment]
> this switch happened with the introduction of global cache

Is the cache global for my project or global for my user?

**Comment by f-f** [comment]
What we call "global cache" in Spago is "per user", while the project cache is called "local cache"

If you disable the global cache then Spago won't have any references to GitHub repos to download tarballs from, so it will `git clone` them in your local cache

[Here's](https://github.com/spacchetti/spago/blob/master/README.md#how-does-the-global-cache-work) an explanation of how the global cache works if you want to know more

**Comment by f-f** [comment]
@Profpatsch did this work for your usecase?

**Comment by Profpatsch** [comment]
Yes, thank you!

**Comment by f-f** [comment]
You're welcome 🙂
