### ISSUE TITLE
Install packages that have `purescript-` prefix

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#367]
Right now if you try to install a package with the `purescript-` prefix, you get an error message:
```
$ spago install purescript-parsing
spago: The following packages do not exist in your package set:
  - purescript-parsing, but `parsing` does, did you mean that instead?                                          
```

Instead of erroring out, we should instead just drop the `purescript-` prefix and install the right package

**Comment by joneshf** [comment]
Is this only a change to the `install` command? Will packages explicitly set as having the `purescript-` prefix in a package set keep their prefix?

**Comment by googleson78** [comment]
I'm for setting them **without** the prefix and issuing a warning about this.

**Comment by f-f** [comment]
@joneshf this is a change affecting all the code searching for dependencies, since we'll have to change the [`getTransitiveDependencies`](https://github.com/spacchetti/spago/blob/77fec6dcb765a4bc93220b308b20930176dd04a7/src/Spago/Packages.hs#L120) function.

In there we try to match on the name provided by the user and only in case of not found we try to drop the prefix and error out. So yeah, packages with the prefix in the set will of course keep the prefix, this is just a UX optimization

I also agree with @googleson78 that we should output a warning about this

**Comment by joneshf** [comment]
Gotcha, thanks for the explanation!

**Comment by f-f** [comment]
You're welcome 🙂

**Comment by jhrcek** [comment]
It seems nobody is working on this, so I'll take a look at this issue. If I don't send a PR within a week, consider my attempt failure :)

**Comment by f-f** [comment]
@jhrcek thanks! Let me know if you need any more details about the code/spec for this 😊

**Comment by jhrcek** [comment]
Implemented in https://github.com/spacchetti/spago/pull/443
