### ISSUE TITLE
Improve AppVeyor caching

### ISSUE THREAD

**Issue by joneshf** [spacchetti/spago#368]
Have you seen the [improvements to AppVeyor caching][dhall-haskell] that `dhall-haskell` recently did? Might drop times in a similar way. Looks like the main thing is to [quote the entire line when environment variables are used][quote].

I'm more than happy to put a PR together if you'd like.

[dhall-haskell]:  https://github.com/dhall-lang/dhall-haskell/pull/1207
[quote]: https://www.appveyor.com/docs/build-cache/#configuring-cache-items

**Comment by f-f** [comment]
Yep, I'm including them in #362 together with some other amount of small fixes 🙂

**Comment by joneshf** [comment]
Cool!
