### ISSUE TITLE
Some tags cannot be installed

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#373]
It turns out our way of fetching git repos doesn't work with all tags. This is because we use `git init && git remote add origin .. && git fetch origin`, and for some reason that doesn't fetch all tags.

It's possible to replicate with the following addition:
```
let additions =
  { graphql =
      mkPackage
        [ "prelude"
        , "console"
        , "effect"
        , "typelevel-prelude"
        , "aff"
        , "aff-promise"
        , "nullable"
        , "argonaut-core"
        , "maybe"
        ]
        "https://github.com/hendrikniemann/purescript-graphql.git"
        "v1.0.1"
  }
```

The `v1.0.1` tag exists but it's not fetched by `git fetch`. To fix this we should just use `git clone`

**Comment by joneshf** [comment]
If you pass the [`--tags` flag](https://stackoverflow.com/a/20608181/1549047), would that solve the issue?

**Comment by joneshf** [comment]
Oh, nevermind. I see it was already addressed.
