### ISSUE TITLE
Serve generated docs

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#379]
When doing `spago docs` one has to start a webserver in order to get the nice searchbar, and that adds friction.

Instead we should serve the docs with [wai-app-static](https://www.stackage.org/package/wai-app-static)

**Comment by klntsky** [comment]
Why would we need to start a webserver?

It works with `file://` for me.

**Comment by f-f** [comment]
Then we should at least display a link to it in `spago docs` (though I'm not sure how it would work on Windows, where the webserver thing will work for sure)

**Comment by klntsky** [comment]
> Then we should at least display a link to it in spago docs

You mean, something like this:

```
Docs generated. Index is at "./generated-docs/index.html"
Link: file:///absolute/path/to/project/generated-docs/index.html
```

?

Then we could also add `--open` flag to either `spago docs` or `docs-search build-index`, to open that link in the browser.

**Comment by klntsky** [comment]
Using one of these:

https://hackage.haskell.org/package/open-browser

https://www.npmjs.com/package/open

**Comment by DStranger** [comment]
Hi guys! I'd like to give this one a try.
