### ISSUE TITLE
Watch: "quit" command doesn't do anything

### ISSUE THREAD

**Issue by stkb** [spacchetti/spago#389]
At first I thought this was another Windows problem that the watch wasn't quitting, but then [from reading the code](https://github.com/spacchetti/spago/blob/ac94f5c21c2d9ac15849de4f6bc311df9eebd69e/src/Spago/Watch.hs#L134-L160) it seems that nothing is actually done when a "quit" command is read and it just loops and waits for the next command?

**Comment by f-f** [comment]
@stkb oops, yeah you're right 😄
