### ISSUE TITLE
Provide some spacchetti package management commands

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#4]
See https://github.com/justinwoo/spacchetti/issues/16

**Comment by justinwoo** [comment]
Personally, I am very happy using my Perl scripts, but someone may want to implement some of these in this CLI.

**Comment by dariooddenino** [comment]
Just gave it a quick try, and thought about some things that would be nice:

1) A `add-package` command that adds packages to `psc-package.json`
2) A `add-from-bower` command that appends new packages in `packages.dhall`, and then calls `add-package`
3) A `clear-cache` command that deletes .psc-packages, or `install` that deltes the folder and runs `psc-package install` afterwards.
4) Deal somehow with an existing project's `psc-package.json`. If it's unreasonable to pickup the settings, at least abort with an error message.

If they sound reasonable to you, I can open them as separate issues and start working on them.

**Comment by dariooddenino** [comment]
@justinwoo 
Upgrading an existing project is probably more annoying than what I initially thought. 
With all the possible combinations of existing `.psc-package.json`, `packages.dhall` and `--force` I feel like it would be giving the user false expectations that things will just work.

Maybe the best thing is to remove `.psc-package.json` from the files checked by `local-setup`, and just "upgrade" it with  `jq '. + { set: "local", source: ""}'`.
This can lead to a broken setup if one of the packages is not in the default spacchetti repo, but we could just print a warning message.

**Comment by justinwoo** [comment]
Sounds fine, though probably we want to not just call jq in reality. Wonder how much aeson would add to the build times/size compared to any other solution for JSON
