### ISSUE TITLE
TODO: update "docs"

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#40]
There are various places where spacchetti-cli and such are referenced, so they should at least be updated to reference this project after releases.

**Comment by f-f** [comment]
Should we track this here? Where are these docs located?

**Comment by f-f** [comment]
@justinwoo it looks like most of the references to `spacchetti-cli` from the link up there have been removed or redirected to spago (and the ones missing are "ecosystem surveys", so they will eventually be updated by their owners), so I'll close this issue (feel free to reopen if you think we should go and fix the remaining refs)
