### ISSUE TITLE
"bundle-module --watch" on Windows fails with a mingled path

### ISSUE THREAD

**Issue by fsoikin** [spacchetti/spago#401]
## Repro:

```
> cd C:/o; md spago-bug; cd spago-bug

> npm i spago
...

> npx spago version
0.9.0.0

> npx spago init
...

> npx spago bundle-module --main Main --to ./foo.js
... (success) ...

> npx spago bundle-module --main Main --to ./foo.js --watch
Installation complete.
CreateFile "C:\\o\\spago-bug\\o\\spago-bug\\.spago\\console\\v4.2.0\\src\\": does not exist (The system cannot find the path specified.)
Type help for available commands. Press enter to force a rebuild.

watched
C:\o\spago-bug\.spago\console\v4.2.0\src\**/*.purs
C:\o\spago-bug\.spago\effect\v2.0.1\src\**/*.purs
C:\o\spago-bug\.spago\prelude\v4.1.1\src\**/*.purs
C:\o\spago-bug\.spago\psci-support\v4.0.0\src\**/*.purs
C:\o\spago-bug\src\**/*.purs
C:\o\spago-bug\test\**/*.purs

build
CreateFile "C:\\o\\spago-bug\\o\\spago-bug\\.spago\\console\\v4.2.0\\src\\": does not exist (The system cannot find the path specified.)
Type help for available commands. Press enter to force a rebuild.
```

## Notes
* Note how Spago tries to open a file with part of the path repeated - `C:\o\spago-bug\o\spago-bug\...`. Such file, naturally, does not exist, so the call fails.
* Touching `src/Main.purs` does not have any effect.
* This doesn't happen without the `--watch` flag. Bundling alone works fine.
* This does _not_ reproduce on Linux (Ubuntu Xenial).
* Have not tried on macOS.
* Versions (just in case)
  * Windows 10 build 18970.1005
  * Node 10.15.3
  * PureScript 0.13.3

**Comment by f-f** [comment]
It looks like this might be the same issue described in https://github.com/spacchetti/spago/issues/380#issuecomment-524583489 which was fixed in #387 which is on `master` but not released yet

I'll cut a release in the next days (see #398) but in the meanwhile you could try out building the current master to see if it fixes the issue for you

**Comment by fsoikin** [comment]
Definitely looks like the same issue from description.
Will try to build master.

**Comment by fsoikin** [comment]
Yes! `master` works fine! (plus, the `quit` command works now)
Thank you @f-f !

**Comment by f-f** [comment]
You're welcome 🙂

**Comment by gasi** [comment]
Grazie mille, @f-f! 🙇
