### ISSUE TITLE
`-watch` commands error when source directories are missing

### ISSUE THREAD

**Issue by elliotdavies** [spacchetti/spago#406]
Say `spago.dhall` includes a `sources` configuration like the following, which is the default:

```
sources = [ "src/**/*.purs", "test/**/*.purs" ]
```

but you delete the `test` directory. Running `spago build` (for example) will log this warning but otherwise proceed to compilation:

```
purs compile: No files found using pattern: test/**/*.purs
```

However `spago build -w` will throw this error and go no further (the file watching still works but it never gets round to compiling):

```
getDirectoryContents:openDirStream: does not exist (No such file or directory)
Type help for available commands. Press enter to force a rebuild.
```

I'd guess the differing behaviour might come from here https://github.com/spacchetti/spago/blob/add6ec7ac9429d251c80f518052ebdcc9ca69759/src/Spago/Build.hs#L88-L90 but I haven't investigated properly yet.

**Comment by f-f** [comment]
@elliotdavies yep, it looks like you're on the right track! In fact, the compiler uses the same `Glob` library that we use, and it checks that the glob is not empty before including it - see [here](https://github.com/purescript/purescript/blob/4949b0428522b001c99c14d4d755aa6b9d237355/app/Command/Compile.hs#L78) - so we should also try to avoid watching a folder that doesn't exist
