### ISSUE TITLE
Small package.dhall docs improvement

### ISSUE THREAD

**Issue by alextes** [spacchetti/spago#408]
In the template, specifically [this line](https://github.com/spacchetti/spago/blob/master/templates/packages.dhall#L67), the example shows `"package-name"` by which it appears to mean a package name but _without_ the `"`. In other words, the package name should be a label, not a string, as the example shows. This is confusing however, as the documentation naturally also uses `"` to indicate you should use a string.

The proposal would be to remove the `"` for the label. Am I making sense? 😄 

Thanks for an awesome tool 🙌 !

**Comment by f-f** [comment]
@alextes thanks 🙂 And indeed you're right, they should be labels!
