### ISSUE TITLE
Cache transitive dependencies

### ISSUE THREAD

**Issue by felixSchl** [spacchetti/spago#409]
The call to [`getTransitiveDeps`](https://github.com/spacchetti/spago/blob/add6ec7ac9429d251c80f518052ebdcc9ca69759/src/Spago/Packages.hs#L118) can get quite slow for larger projects, even on a decent machine.

I found at least one relevant reference to this here: https://github.com/spacchetti/spago/issues/110#issuecomment-463518492.

I am wondering if we could not simply cache the transitive deps based on the hash of the dhall files, perhaps, or even take the hash of the `PackageSet` type, if at all possible.

**Comment by f-f** [comment]
@felixSchl yeah, great points! I think it would be ok to cache things based on the hash of Dhall files, but it might not be necessary if we had a faster implementation. I think the current implementation is fairly naive and there might be lots of space for improvement, as noted in the comment you linked

**Comment by justinwoo** [comment]
my other question for this is would this work with a function written in dhall?

**Comment by f-f** [comment]
@justinwoo as I understood it they did not mean to write the function in Dhall, but to use the hash of `spago.dhall` or `packages.dhall` to identify the right cache to use for caching the list of transitive dependencies for every package
