### ISSUE TITLE
Feature request: Add support for --before/--then/--else flags

### ISSUE THREAD

**Issue by felixSchl** [spacchetti/spago#410]
Pulp has a handful of very useful options to run a command when compilation starts, fails, and succeeds: `--before <string>`, `--else <string>`, and `--then <string>`, respectively. This is useful in combination with `--watch` in order to, for example, run some post-processing script on the output. Currently the only way to achieve the same is using an external file watcher and run `spago build && foobar` on every file change. Aside from the additional overhead of getting set up properly for every project, there's also the overhead of cold-starting a build every time (see also: #409, #110) which slows down rebuilds considerably.

**Comment by f-f** [comment]
Yeah this sounds reasonable! Though I'd be curious about your specific usecase, to see if we can provide some specific integration before opening up to the full `before`/`then`/`else` workflow

**Comment by felixSchl** [comment]
It's a very project specific workflow where we need to run a script over the generated JS to fix up some internal require paths based on the build output. To be honest I have not used `--before` at all and only discovered it when doing my research for opening this issue, but it seems to make sense to have if we do end up with some sort of `--then` and `--else`.

It's not a super urgent feature request by any means because it's really just been a workflow enhancement. That said, if you  do think it's a worth while feature to bring in (in terms of maintenance cost going forward,) I'd be happy to take a stab at it.

**Comment by FungusHumungus** [comment]
I used the `--then` flag to post a notification once pulp had finished building.

```
pulp --watch --then 'notify-send built' build -O -t ../dist/ps.js
```

It was quite handy as I didn't have to swap to the terminal to check to see when everything was ready to refresh the browser.

**Comment by f-f** [comment]
Yeah this sounds good, let's go with the way `pulp` does it since it seems to be a nice design!

**Comment by felixSchl** [comment]
I wonder if we can achieve the same thing in a more composable manner. Imagine spago only reporting to stderr during `--watch` and only reporting build status updates line by line on stdout. Then one could compose quite easily downstream using ordinary shell tooling.

Imagine some structured output like this:

```
* Build starting
0 Build succeeded
1 Build failed
```

it would be trivial to do sth like:

```
spago build --watch | while read -r status; do ...; done
```

Then again, that precludes spago from cancelling long-running post-build commands. `--then` to pulp would be canceled when the user triggered a rebuild, which I thought was really useful, too.

**Comment by f-f** [comment]
@felixSchl yeah this is also a very interesting approach. Note that starting with #475 logging is starting to move to `stderr`, so this option is also totally viable (and good by me). On the other hand, the `--before/--then/--else` approach might be more flexible because of the cancelability aspect
