### ISSUE TITLE
glibc2.27 introduced as dependency in 0.10.0

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#427]
you can choose to do nothing about this, but it might be good to do something about it.

## What

glibc2.27 is now a runtime dependency of 0.10.0, whereas the previous versions did not do anything requiring this.

## Why

good question. some infection happened somewhere.

## How

Try using `xenial`, e.g. on Travis, and install `spago` via npm.

```
> spago install
spago: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by spago)
```

Seems expected: https://packages.ubuntu.com/source/xenial/glibc

## Non-solution

* "static compilation"
* "use easy-purescript-nix"

## Potential solutions

* find culprit and purge
* build matrix, release for multiple glibc versions instead of only on bionic (https://github.com/spacchetti/spago/blob/760faf6d428e431e377d74ec77cb5dceef37eb81/.travis.yml#L4)
* advisory about non-usability on xenial (16.04LTS) via npm (upgrade to 18.04LTS, "patch ELF", "use easy-purescript-nix")

**Comment by f-f** [comment]
@justinwoo great catch. I'm pretty sure this got in with #395, so I guess we could try downgrading LTS (and GHC) again?

**Comment by justinwoo** [comment]
it might be worthwhile to have both a static and dynamically linked executable available for release. sounds like a pain, but can still be worthwhile for compatibility and for avoiding other unexpected behaviors.

**Comment by f-f** [comment]
@justinwoo great point. I'd want to ship the static one to npm though, so that the majority of the users would skip the pain and who needs the dynamic binary can download it directly

**Comment by justinwoo** [comment]
if you want to make it truly enterprise, you can require environment variables to determine which binary is downloaded

**Comment by f-f** [comment]
@justinwoo I'm afraid I'm not that good at JS to be able to patch the installer, so I'll spawn another issue to implement that once we ship the static binaries
