### ISSUE TITLE
MoveFileEx permission denied (Access is denied.) when using `npx spago build`

### ISSUE THREAD

**Issue by bjornkihlberg** [spacchetti/spago#429]
Hello,

I actually "fixed" my problem right before I sent the below description but I thought I'd report this anyway if it's either a bug or the tutorial needs adjusting or maybe someone else runs into this problem.

I tried to install [spago](https://www.npmjs.com/package/spago) and [purescript](https://www.npmjs.com/package/purescript) in a local npm project with `npm install -D spago purescript`. [In the tutorial](https://github.com/spacchetti/spago#installation) it says "The **recommended** installation method for Windows, ..." is
```
npm install -g spago
```
Either `npm install -D spago` should work or the tutorial should mention something along these lines "On Windows spago **has** to be installed with npm globally in order to work properly."

## Before I figured out how to solve this:

---
I'm running Windows 10, and tried doing all of this with a console with admin privileges and it still didn't work.

I've tried to add [hareactive](https://github.com/funkia/purescript-hareactive) to my `packages.dhall` file. This is what I've tried:
```dhall
let additions =
        { hareactive =
            { dependencies =
                [ "prelude"
                , "functions"
                , "maybe"
                , "partial"
                , "effect"
                , "aff"
                , "web-dom"
                , "web-uievents"
                ]
            , repo =
                "https://github.com/funkia/purescript-hareactive.git"
            , version =
                "v0.1.2"
            }
        }
```
as well as adding this to `spago.dhall`:
```dhall
{ name =
    "my-project"
, dependencies =
    [ "effect", "console", "psci-support", "hareactive" ]
, packages =
    ./packages.dhall
, sources =
    [ "src/**/*.purs", "test/**/*.purs" ]
}
```
When running the command `npx spago build` I get this error in the console:
```
Installing "hareactive"
spago.exe: Installation failed.

Error:

MoveFileEx ".spago\\__download-hareactive-v0.1.2-19170c98a4e76b3a\\download" Just "E:\\Workspace\\learningdhall2\\.spago\\hareactive\\v0.1.2": permission denied (Access is denied.)
```

**Comment by bjornkihlberg** [comment]
Looks like I was wrong! It was only a coincidence that it worked right after I had installed spago globally. If I try to run `spago build` multiple times eventually it will succeed. Here's some output from my console:
```
PS E:\Workspace\tictactoe> spago install hareactive       
Installing 19 dependencies.
Searching for packages cache metadata..
Recent packages cache metadata found, using it..
Copying from global cache: "datetime"
Copying from global cache: "now"
Copying from global cache: "nullable"
Copying from global cache: "foreign"
Copying from global cache: "ordered-collections"
Copying from global cache: "functors"
Copying from global cache: "contravariant"      
Copying from global cache: "web-storage"        
Copying from global cache: "parallel"
Copying from global cache: "const"
Copying from global cache: "media-types"

MoveFileEx ".spago\\__download-hareactive-v0.1.2-8968d4b36ec7fff4\\download" Just "E:\\Workspace\\tictactoe\\.spago\\hareactive\\v0.1.2": permission denied (Access is denied.)
PS E:\Workspace\tictactoe> spago install hareactive
WARNING: configuration file was not updated. You should have a record with the `dependencies` key for 
this to work.
Installing 2 dependencies.
Searching for packages cache metadata..
Recent packages cache metadata found, using it..
Copying from global cache: "web-html"
Installing "hareactive"
Installation complete.
PS E:\Workspace\tictactoe>
```

I verified that it builds as well after importing modules from the package. Don't know yet if the package works properly.

**Comment by f-f** [comment]
Hi @bjornkihlberg, thanks for the report!

I'm a bit confused because even if Spago seems to be building, there still seems to be something wrong, as the thing is still complaining about permissions. I wonder if someone else on Windows can replicate? (e.g. @stkb?)

**Comment by stkb** [comment]
I can't replicate I'm afraid, with those package.dhall and spago.dhall files, both `spago build` and `spago install hareactive` both work fine (v10.0.0).

The (sporadic) permission denied error could come from some timing issue and a file still being in use. If I think of something I'll report back, of course

**Comment by f-f** [comment]
@stkb thanks!

I guess we can close this until we find a replication then?

**Comment by stkb** [comment]
Yeah I have nothing more to add right now.

**Comment by f-f** [comment]
Alright I'll close this one, but I noticed a bug in the output of the report here, so I opened #436

**Comment by meowjesty** [comment]
This was happening to me while I was trying to install a package with the vscode purescript ide running, it probably locks up the files like @stkb was saying.

If anyone else happens to face this issue:
- close vscode (or stop whatever IDE you're running), and do a `spago install` from your terminal.

**Comment by whitecolor** [comment]
Had the same issue have to close VScode to resolve.

**Comment by jquesada2016** [comment]
Same thing here, I didn't have any PureScript extensions installed as I was just getting started, and ran into this issue. Closing VS Code and running from the terminal fixed it for me.

Perhaps a note to the docs could help? As I could imagine this discouraging less willed beginners.

**Comment by wclr** [comment]
If I'm not mistaken, adding `"**/.spago/**": true,` to `files.watcherExclude` vscode settings should solve this.
