### ISSUE TITLE
Avoid watching dependencies in `.spago` directory

### ISSUE THREAD

**Issue by elliotdavies** [spacchetti/spago#430]
(Split out from discussion in #420.)

When running `spago build --watch` we monitor changes to local (i.e. monorepo) dependencies, but we also watch for changes in the `.spago` directory. I'm not sure if there are any performance implications, but it's unintended behaviour and has potential to cause weird edge cases (as in #420) so we ought to stop doing it 😀

**Comment by f-f** [comment]
Fixed in #446
