### ISSUE TITLE
Automate publishing also the new name `spago` on NPM

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#44]
This guy doesn't even use this name anymore: https://www.npmjs.com/package/spago (https://github.com/FormBucket/xander#readme)

We could ask him to give the name

**Comment by f-f** [comment]
Update: we got the `spago` name on `npm`, so I'll rename this issue to track the new deployment

**Comment by justinwoo** [comment]
Nice, holy hell

**Comment by justinwoo** [comment]
http://npmjs.com/spago

**Comment by f-f** [comment]
@justinwoo I published it there by hand, and I intended to leave this issue open to track the Travis implementation of automating the publishing.

I think the only way we can automate it with Travis is to use [build stages](https://docs.travis-ci.com/user/build-stages/)

**Comment by f-f** [comment]
As detailed in #115 we just rename the current publishing pipeline instead of going through the Travis trouble.

I'll leave this open to remind us to do the `npm deprecate purescript-spago`

**Comment by f-f** [comment]
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/5480361/53688357-779b0380-3d4b-11e9-98d2-a4c6515fd24d.png">
