### ISSUE TITLE
Cleanup bump-version tests

### ISSUE THREAD

**Issue by jhrcek** [spacchetti/spago#440]
The tests for bump-version command are slower compared to other tests (each taking ~7s on my pc). In my opinion it doesn't make sense to have so many end2end tests checking this functionality.
I think we should reduce [these tests](https://github.com/spacchetti/spago/blob/52ddd50747bd139474008780cc612396a4b5477b/test/BumpVersionSpec.hs#L73-L94) to maybe 1-2 end2end tests (using spago cli directly) and the rest should be deleted and replaced by unit/property tests of `getNextVersion`. WDYT?

**Comment by f-f** [comment]
@jhrcek sounds great! Faster tests are always nice 🙂

**Comment by jhrcek** [comment]
Here are just some numbers for referene:

Test suite duration as reported by Hspec `Finished in X seconds`, measured on my machine and averaged over 5 runs:
`stack test`: ~ 118 seconds
`stack test --test-arguments '-m BumpVersion'`: ~ 69 seconds

So BumpVersion tests take about 57% time of the entire test suite.

**Comment by jhrcek** [comment]
Resolved in https://github.com/spacchetti/spago/pull/445
