### ISSUE TITLE
Add a "getting started with Parcel" to docs

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#456]
We have a "getting started" guide in the docs, but that's quite minimal. Leon on Slack noted how we could have a slightly more detailed "getting started with Parcel" to show how one could get a JS project to build with Spago + Parcel:

> i guess what i was actively searching in the Spago Readme was some chapter "Getting started: Simple development Setup with Parcel" or something, that explains a typical workflow
> - compile code using spago build into output/Main/index.js
> - create index.html in project root and load an index.js file
> - create index.js, require the compiled purescript file in there and call the main method of it
> - call parcel index.html to start the dev-server
>
> or something simmilar. the big problem for me was that I'm rather new to Puresript and not that experienced with the JS build ecosystem as well (Parcel, etc), so things like "most of the time, you'll have some kind of index.html, that does some stuff, where you can then import the Purescript File and call main " dont really make it clear what to do when just trying to set up a simple project and get started.
it all makes sense as soon as you understand how the things connect with one another, but as long as you don't, the instructions are rather unclear. maybe a beginners-guide or something that talks about the most common setups and gives examples would be great. maybe having a live-server directly integrated into spago would be great as well

**Comment by Benjmhart** [comment]
I'll take a run at this one since I've set up projects to do this

**Comment by swuecho** [comment]
and webpack? 

trying to use the generated index.js with webpack, leading to "Cannot assign to read only property 'exports' of object '#<Object>'"

**Comment by Benjmhart** [comment]
@swuecho - currently the guide is for purescript,  however I might have some time to add steps to configure for webpack and nodemon (for server-side projects) at some point.

**Comment by f-f** [comment]
Fixed in #461

**Comment by Benjmhart** [comment]
@f-f Actually I think I'll add a guide for nodemon and (possibly) webpack as well.   I'll see if I can get a PR up in a reasonable amount of time.

**Comment by swuecho** [comment]
@Benjmhart  https://github.com/purescript/purescript/issues/3613 the module format make it not so easy to work with webpack.

**Comment by Benjmhart** [comment]
@swuecho - I'm writing webpack docs today.   if you can work with parcel you can work with webpack.

**Comment by Benjmhart** [comment]
@swuecho - there is a PR up relating to your request:https://github.com/spacchetti/spago/pull/473

you can also look at the docs in my fork to see how to get a webpack development server up and running with Spago and Purescript: https://github.com/Benjmhart/spago

**Comment by swuecho** [comment]
@Benjmhart  Thanks. I did not know there is `purs-loader` out there. after I copied the loader in my webpack config works greet.  

I was expected that I can import the js output directly in js code.

**Comment by Benjmhart** [comment]
@swuecho  - you can definitely use a webpack in the way you describe, with spago producing an output in js and webpack bundling the JS as a dependancy, however webpack should really be your end-to-end development bundler, with spago being used more for managing dependancies in that workflow.
