### ISSUE TITLE
Problem installing spago behind proxy

### ISSUE THREAD

**Issue by beebpeeb** [spacchetti/spago#460]
Although the initial `npm install` of `spago` works behind a proxy, the subsequent `install.js` to fetch and install the binary does not.

Would it be possible to use an npm library which respects `$http_proxy` for this installation step?

**Comment by beebpeeb** [comment]
I have a fix for this issue. Is the preferred workflow to fork the repo and open a pull request?

**Comment by f-f** [comment]
@beebpeeb that's great news! And yes what you describe is the preferred workflow 🙂

**Comment by daveman1010221** [comment]
Hello! How do I get this fix in almost-April of 2020? I am using npm 6.14.4 and nodejs 13.12.0 on Ubuntu 19.10. As I found this error, I'm assuming I don't have this fix in my npm of spago yet.

**Comment by f-f** [comment]
@daveman1010221 this shipped in [0.13.0](https://github.com/purescript/spago/releases/tag/0.13.0), and we already have `0.14.0` on npm, so maybe you're stumbling on a different issue?

**Comment by daveman1010221** [comment]
In fact, it was a different issue. Installation on my system required --unsafe-perm.

**Comment by daveman1010221** [comment]
Wow, I didn't know you _could_ update your node prefix, until you asked that question. I've done so now. Lots of mysteries solved. Thanks. :-)
