### ISSUE TITLE
Dhall deprecations

### ISSUE THREAD

**Issue by Benjmhart** [spacchetti/spago#476]
There are a number of deprecation warnings in ./src/Spago/Config.hs stemming from usage of Dhall.TypeCheck.X.   

We ought to fix that up unless there is a real reason to continue using the deprecated features.   

@f-f  - is there a reason not to resolve?

**Comment by f-f** [comment]
@Benjmhart no, they should be fixed! I'm fixing this as part of #458

**Comment by f-f** [comment]
Fixed in #486
