### ISSUE TITLE
`Missing file ./packages.dhall` when not in project dir

### ISSUE THREAD

**Issue by srghma** [spacchetti/spago#478]
suppose your project is in

```
$ ls -al ~/projects/spago2nix/
total 148
drwxr-xr-x  10 srghma users  4096 Oct 27 18:55 .
drwxr-xr-x  13 srghma users  4096 Oct 27 17:46 ..
drwxr-xr-x   2 srghma users  4096 Oct 27 17:46 bin
-rw-r--r--   1 srghma users   456 Oct 27 17:46 build-project.nix
-rw-r--r--   1 srghma users   436 Oct 27 17:46 ci.nix
-rw-r--r--   1 srghma users  1313 Oct 27 17:46 default.nix
drwxr-xr-x   8 srghma users  4096 Oct 27 19:49 .git
drwxr-xr-x   3 srghma users  4096 Oct 27 17:46 .github
-rw-r--r--   1 srghma users   131 Oct 27 17:46 .gitignore
-rw-r--r--   1 srghma users 22470 Oct 27 17:46 logo-256.png
drwxr-xr-x 327 srghma users 20480 Oct 27 18:57 output
-rw-r--r--   1 srghma users   334 Oct 27 17:46 package.json
-rw-r--r--   1 srghma users   259 Oct 27 18:55 packages.dhall
-rw-r--r--   1 srghma users  2270 Oct 27 17:46 README.md
drwxr-xr-x  74 srghma users  4096 Oct 27 19:00 .spago
drwxr-xr-x   2 srghma users  4096 Oct 27 18:17 .spago2nix
-rw-r--r--   1 srghma users   392 Oct 27 18:55 spago.dhall
-rw-r--r--   1 srghma users 30447 Oct 27 18:17 spago-packages.nix
drwxr-xr-x   2 srghma users  4096 Oct 27 19:11 src
drwxr-xr-x   2 srghma users  4096 Oct 27 17:46 test
```

when you do

```
$ cd ~/projects/spago2nix/
$ spago --config ./spago.dhall list-packages --filter transitive --json

....everything is fine
```

but when you do

```
$ cd ~/projects/
$ spago --config spago2nix/spago.dhall list-packages --filter transitive --json
spago: 
↳ ./packages.dhall

Error: Missing file ./packages.dhall

22│     ./packages.dhall

22:5
```

 I believe that path to `./packages.dhall` should be derived from `./spago.dhall` `packages` option

```dhall
{-
Welcome to a Spago project!
You can edit this file as you like.
-}
{ sources =
    [ "src/**/*.purs", "test/**/*.purs" ]
, name =
    "my-project"
, dependencies =
    [ "console"
    , "generics-rep"
    , "kishimen"
    , "node-fs-aff"
    , "parallel"
    , "prelude"
    , "simple-json-utils"
    , "sunde"
    , "validation"
    ]
, packages =
    ./packages.dhall
}
```

**Comment by srghma** [comment]
just checked what will be if I rename `./packages.dhall` to `./mypackages.dhall`

and it worked

```
{-
Welcome to a Spago project!
You can edit this file as you like.
-}
{ sources =
    [ "src/**/*.purs", "test/**/*.purs" ]
, name =
    "my-project"
, dependencies =
    [ "console"
    , "generics-rep"
    , "kishimen"
    , "node-fs-aff"
    , "parallel"
    , "prelude"
    , "simple-json-utils"
    , "sunde"
    , "validation"
    , "optparse"
    ]
, packages =
    ./mypackages.dhall
}
```

```
spago --config ./spago.dhall list-packages --filter transitive --json
....
```

**Comment by srghma** [comment]
also checked what will happen if I rename `./spago.dhall` to `./myspago.dhall`

worked too


```
spago --config ./myspago.dhall list-packages --filter transitive --json
```

**Comment by srghma** [comment]
I dont understand why we have the `./packages.dhall` file?

what's the idea of having it? 

wouldn't it be easier if we had only `./spago.dhall` file, and not `spago.dhall` + `./packages.dhall`?

**Comment by f-f** [comment]
@srghma thanks for the replication example, I can replicate this and it's a bug

If you run with `-v` you can see that the last log line is coming from this function, so I think the bug is somewhere here (cc @elliotdavies, any idea why this is happening?):
https://github.com/spacchetti/spago/blob/261f34cfa4155f4fac5b15b60f746c7b5b563e73/src/Spago/PackageSet.hs#L262-L271

Re unifying `packages.dhall` and `spago.dhall`: the files are separate mainly for allowing us to edit the AST without much hassle. We could potentially unify them, but that would require great care to cover all the corner cases and I'm not sure it's a priority at the moment

**Comment by elliotdavies** [comment]
Yeah, we're incorrectly assuming `spago.dhall` lives in the same place as Spago was invoked from:

- config file lives at `/a/b/spago.dhall`
- package-set file lives at `/c/packages.dhall`
- `readImports` correctly calculates the relative path from the first to the second as `../../c/packages.dhall`
- `freeze` is invoked with that relative path directly, not taking into account that it needs to prepend `/a/b/`

I think this should be a simple fix - I'll take a look at it :smile:

**Comment by f-f** [comment]
@elliotdavies would it help if we had the config as an absolute path? (which is the fix for #472)

**Comment by elliotdavies** [comment]
@f-f I don't think it should make a difference in this case - one way or another we still need to combine the location of the config with the relative path returned from `readImports`

**Comment by elliotdavies** [comment]
@f-f Hmm I wasn't quite right, it's actually failing on `Parser.exprFromText` inside `readImports`. So perhaps it's a Dhall issue? (We may still need to change the path we're passing to `freeze` but right now I can't get far enough to test that.)

**Comment by f-f** [comment]
@elliotdavies if the problem is in Dhall code then I have the feeling that having the absolute path there might fix the issue.

On the other hand, this bug springs up the philosophical question of "should we care about project roots", i.e. if I run
```
$ spago -x foo/spago.dhall build
```
..then what's my project root, `./` or `./foo`?

Right now we'd have `.spago` in `./`, but `./output` in `./foo`, which seems inconsistent 🤔

**Comment by elliotdavies** [comment]
I've submitted a PR to fix this - needed to pass an option to Dhall's `load` to set the base directory for import resolutions.

I'll take a look at #472 in a bit too.

On the project root, as of #422 the `output` folder will move to wherever the root `packages.dhall` is, right? So I think we're pretty much considering that to be the root, if we care at all.
