### ISSUE TITLE
Can't use stdin with `spago run`

### ISSUE THREAD

**Issue by kohanyirobert** [spacchetti/spago#488]
Given this code

```
module Main where

import Effect (Effect)
import Effect.Console (log)
import Node.Encoding (Encoding(..))
import Node.Process (stdin)
import Node.Stream (onDataString)
import Prelude (Unit)

main :: Effect Unit
main = do
  onDataString stdin UTF8 log
```

When I run ```echo "wut?" | spago run``` nothing gets displayed in the console, althought that's my expectation.

After `spago build` doing `echo "wut?" | node .spago/run.js` works.

**Comment by f-f** [comment]
@kohanyirobert your expectation feels right to me as well, so I put up a fix for this in #490. Note that it includes your example file as a test 🙂
