### ISSUE TITLE
NPM release for `0.11.1`

### ISSUE THREAD

**Issue by csicar** [spacchetti/spago#497]
Could you also update the version on [NPM](https://www.npmjs.com/package/spago)?

The version is still on `0.10.0` at the moment.

**Comment by f-f** [comment]
@csicar yeah sorry, I unpublished that version as I found out that the statically-linked binary for Linux doesn't include `netbase`, so all the connectivity doesn't work. I'll fix that and cut `0.11.2`

**Comment by csicar** [comment]
Thank you for the quick response. No problem. I just wanted to make sure it wasn't forgotten or anything :)

**Comment by f-f** [comment]
@csicar we cannot forget it as the new releases on NPM are cut by CI following the releases happening here - [see the relevant part of the Travis file](https://github.com/spacchetti/spago/blob/28af364791aadf402e743e2d9677852c6063baea/.travis.yml#L159-L167)

**Comment by csicar** [comment]
oh yeah. That's nice

**Comment by csicar** [comment]
Thank you. The AUR-Package is now updated to `0.12.1` as well

**Comment by f-f** [comment]
@csicar thank you! :slightly_smiling_face:
