### ISSUE TITLE
`test` command doesn't work correctly

### ISSUE THREAD

**Issue by starper** [spacchetti/spago#50]
When I run `test` command, I end up with a bunch of `Module Foo.Bar was not found` errors. It just doesn't see modules in `src` folder. So I guess the answer to [this](https://github.com/spacchetti/spago/blob/master/app/Spago.hs#L253) question is "yes" :)

**Comment by f-f** [comment]
@starper good catch! I put that comment there myself, and the fix should be a couple of chars :)
