### ISSUE TITLE
Linux's static binary fails with segmentation fault

### ISSUE THREAD

**Issue by kamoii** [spacchetti/spago#500]
Downloaded `Linux.tar.gz` from release page:
https://github.com/spacchetti/spago/releases/tag/0.11.1.0

Running `spago init` fails with segmentation fault. Haven't analysed the core dump yet.

```
$ mkdir foo
$ cd foo
$ spago init
[info] Initializing a sample project or migrating an existing one..
[1]    281532 segmentation fault (core dumped)  spago init
$ ls
packages.dhall  spago.dhall
$ spago version
0.11.1.0
```

I'm using Arch linux.
```
Linux 5.3.8-arch1-1 #1 SMP PREEMPT @1572357769 x86_64 GNU/Linux
```

**Comment by kamoii** [comment]
Noticed that `spago init` recieves `-v` option. 
```
$ spago init -v
Running `getGlobalCacheDir`
[info] Initializing a sample project or migrating an existing one..
[debug] Running `spago upgrade-set`
[debug] Unable to read file "/home/sino/.cache/spago/package-sets-tag.txt". Error was: /home/sino/.cache/spago/package-sets-tag.txt: getModificationTime:getFileStatus: does not exist (No such file or directory)
[1]    284970 segmentation fault (core dumped)  spago init -v
```
Looks like something wrong with my cache. Deleted the cache and tried again but result was same.

**Comment by kamoii** [comment]
Tried `linux-dynamic.tar.gz`, the shared library version, and now it succeed.

**Comment by kamoii** [comment]
Treid the static version on a different macean and now it succeeds. 
```
Linux 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by f-f** [comment]
@kamoii yes, the static binary is currently broken on some distros, because linking to `glibc` is problematic. I'm going to publish another release switching the binary back to the dynamic one for now
