### ISSUE TITLE
Downloading the spago binary failed.

### ISSUE THREAD

**Issue by gcsolaroli** [spacchetti/spago#503]
I am trying to upgrade my (toy) project to Spago 0.12.0.

Unfortunately, it fails pretty quickly on my Mac (running Catalina 10.15.1).

```
$ nvm install --lts
Installing latest LTS version.
[…]
Now using node v12.13.0 (npm v6.12.0)

$ npm install -g purescript
[…]
+ purescript@0.13.5
added 154 packages from 89 contributors in 6.057s

$ npm install -g spago
/Users/giulio.cesare/.nvm/versions/node/v12.13.0/bin/spago -> /Users/giulio.cesare/.nvm/versions/node/v12.13.0/lib/node_modules/spago/spago

> spago@0.12.0 postinstall /Users/giulio.cesare/.nvm/versions/node/v12.13.0/lib/node_modules/spago
> node ./install.js

+ spago@0.12.0
added 13 packages from 10 contributors in 0.866s

$ spago
Downloading the spago binary failed. Please try reinstalling the spago npm package.
```

Any idea on what I am doing wrong?

**Comment by gcsolaroli** [comment]
Out of curiosity, I check the content of the linked file listed in the logs:

```
$ cat /Users/giulio.cesare/.nvm/versions/node/v12.13.0/lib/node_modules/spago/spago
#!/usr/bin/env node
// This file is only used on Windows. In *nix NPM installations it's replaced
// with the actual spago binary.

const cp = require("child_process");

// Ignore SIGINT (Ctrl-C) because we don't want to terminate this process from
// it (#483). Spago.exe will handle it for us
process.on('SIGINT', () => {});

const spago = cp.spawn(__dirname + '/spago.exe', process.argv.slice(2), {stdio: 'inherit'});
spago.on('error', (err) => {
    console.log("Downloading the spago binary failed. Please try reinstalling the spago npm package.");
});
```

Looks like the installer somehow thinks I am using Windows. 😳

**Comment by alextes** [comment]
Release 0.12 switched to static linking, changing the naming of the released assets in the instance of macOS from `osx.tar.gz` to `osx-static.tar.gz`. The install script still expects the old naming [here](https://github.com/spacchetti/spago/blob/master/npm/install.js#L12).

As for the confusing contens of your spago executable (`which spago`). The script typically replaces the contents of the executable. Somehow, the Windows contents are the default. I'm not sure why. In any case, it is detecting your OS correctly but failing to take the appropriate action.

**Comment by f-f** [comment]
@alextes oh, great catch. I did this change in #502 thinking that it would affect only Linux but of course macOS is affected too. 

The macOS binary is actually not statically linked, only the name is wrong. I'll put up a fix and cut a new release ASAP

**Comment by gcsolaroli** [comment]
Thanks @alextes, with your suggestion I am able to start using spago@0.12.0 right away.
