### ISSUE TITLE
add backup docs-search-app.js and purescript-docs-search to templates directory

### ISSUE THREAD

**Issue by cdepillabout** [spacchetti/spago#510]
It appears that there is code in `src/Spago/Templates.hs` that embeds code from the `purescript-docs-search` repo into the spago binary:

https://github.com/spacchetti/spago/blob/a4679880402ead320f8be2f091b25d30e27b62df/src/Spago/Templates.hs#L30-L46

However, the two fallback files specified (`templates/docs-search-app.js` and `templates/purescript-docs-search`) don't actually seem to exist:

https://github.com/spacchetti/spago/tree/a4679880402ead320f8be2f091b25d30e27b62df/templates

**Comment by f-f** [comment]
@cdepillabout that's right, the files are not supposed to be there. If you look at the code for `embedURLWithFallback`, they get downloaded the first time you try to build if they are not there:
https://github.com/spacchetti/spago/blob/a4679880402ead320f8be2f091b25d30e27b62df/src/Spago/TH.hs#L32-L50

We did consider that this is not exactly Nix-friendly, but building this from scratch with Nix is not a priority at the moment, as one can always get a binary with [easy-purescript-nix](https://github.com/justinwoo/easy-purescript-nix/blob/master/spago.nix)

**Comment by cdepillabout** [comment]
@f-f Sorry, I believe I misread the code there!

Originally, I had thought that the `fallback` was supposed to already be in the `spago` repo (and it was only downloaded when missing for some reason), but now I see it is intended to be downloaded on first build.

Sorry for the noise here.
