### ISSUE TITLE
haddock generation broken

### ISSUE THREAD

**Issue by cdepillabout** [spacchetti/spago#511]
Haddock generation appears broken for spago.

When trying to generate haddocks, I get errors like the following:

```
src/Spago/FetchPackage.hs:111:5: error:
    parse error on input ‘-- * if a Package is in the global cache, copy it to the local cache’
    |
111 |     -- * if a Package is in the global cache, copy it to the local cache
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I believe this is caused by an unfortunate feature of `haddock` that doesn't allow haddock-style markup in comments that are not proper haddocks.

--------------------------------------------------------------------------

I recently fixed something in `purescript` similar: https://github.com/purescript/purescript/pull/3745

**Comment by f-f** [comment]
@cdepillabout right, I think I never generated Haddocks for the package ever. Want to have a go at this?

**Comment by cdepillabout** [comment]
@f-f I'll take a look at this and see if I can get something working.
