### ISSUE TITLE
release to hackage

### ISSUE THREAD

**Issue by cdepillabout** [spacchetti/spago#512]
I am currently working on [packaging spago](https://github.com/NixOS/nixpkgs/pull/74557) in nixpkgs.

nixpkgs has a convenient way of (semi-)automatically getting package updates from Hackage for Haskell packages that have been released to Hackage.

It would be nice for us if spago was uploaded to Hackage on every release.

However, I completely understand that it might complicate the release process for spago if the maintainers have to remember to upload it to two separate places.  It seems like most people are pretty happy with the releases to npm, so I can understand if also releasing to Hackage is too much work.  In that case, please feel free to close this with WONTFIX.

**Comment by f-f** [comment]
@cdepillabout yes, I thought about uploading to Hackage, but:
- as you say it's a bunch of additional work. Moreover, the CI setup is already kind of fragile so I'm wary of adding more things to the pile of stuff to maintain there
- I wouldn't want other Haskell packages to depend on this for now, as we'd have to think about versioning and API breakage and so on, and it's already hard even just for the CLI alone.

So I'd say this is not on the table for now, but we might want to upload some `spago-core` package on Hackage once we feel like some of the code can be shared

**Comment by cdepillabout** [comment]
@f-f Thanks for the response.

> as you say it's a bunch of additional work

I definitely agree with this.  I think it is completely reasonable to only have the two release channels (NPM and GitHub releases).

> I wouldn't want other Haskell packages to depend on this for now, as we'd have to think about versioning and API breakage and so on

I don't think there are any hard-and-fast rules for versioning packages on Hackage (aside from most people following the PVP), so personally I'd completely understand if you were to upload Spago to Hackage and have your own versioning policy that doesn't follow the PVP.

---------------------------------------------------------------------

> this is not on the table for now

That definitely makes sense.  Feel free to close this issue (unless you want to keep it open for sometime in the future when you upload some `spago-core` package)!

**Comment by f-f** [comment]
Alright, I'll then close this for now - as I like to keep issues actionable - and let's reopen it when we identify some useful subset of the codebase that could be useful on Hackage
