### ISSUE TITLE
spago build for psgo not working

### ISSUE THREAD

**Issue by danielo515** [spacchetti/spago#517]
Hello!
I'm having problems on macos to run spago build using psgo as backend.
I have Go toolchain installed and I can run go in any terminal.

Here is my spago.dhall:

```dhall
{ name = "my-project"
, dependencies = [ "console", "effect", "psci-support" ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
, backend = "psgo"
}

```

And here is the error I'm getting:

```
➜  spago build
[info] Installation complete.
[info] Build succeeded.
/bin/sh: psgo: command not found
[error] Backend "psgo" exited with error:127
```

I followed all the isntruction shtat I have found and I'm not sure what else should I try or install.
Compiling to JS has no problems.
Thanks in advance.

**Comment by danielo515** [comment]
Ok, I just found the way to solve this. I download a psgo binary and put it on a binary folder that was on my path. After that, everything worked without problem and now I have my native build file called Main. 
This is not a fault on spago at all, it's psgo installation instructions that are not clear, so I'll report this there.
Thanks for this awesome project.

**Comment by f-f** [comment]
You're welcome! And happy to hear you figured out 🙂
