### ISSUE TITLE
Question on additions

### ISSUE THREAD

**Issue by naglalakk** [spacchetti/spago#52]
Hi and thank you for this great repo. I'm thinking about additions. Let's say I try to install the purescript-graphql library. This is not in the default package-set so I add it

    {
        graphql =
        mkPackage
         [ "aff"
         , "argonaut-core"
         , "httpure"
         , "argonaut-codecs"
         ]
         "https://github.com/hendrikniemann/purescript-graphql"
         "master"
    }

I then run spago install and it installs graphql correctly. Now when running spago build I get errors on the dependencies graphql needs (Node.Stream for example). So I add purescript-node-streams etc. Do I do this for every dependency the addition relies on? 

It makes sense for me that I would do this seeing that spago cannot know how to install dependencies from other additional dependencies. Just wanted to be 100% I'm not missing anything.

**Comment by f-f** [comment]
Hi @naglalakk! You're right, `spago` cannot know about dependencies of dependencies (especially if things are not in the package-set, so things will fail to build if:
- you don't specify all the dependencies when adding a package to the set
- even if a package is specified in the set, it's missing some dependencies

More specifically, in your case it looks like you're not specifying all the dependencies of `purescript-graphql`? Looking at its [bower file](https://github.com/hendrikniemann/purescript-graphql/blob/master/bower.json) it seems like not all the dependencies are listed in your addition (e.g. missing `aff-promise` and so on?)

In case a dependency is not in the package-set, IIRC `spago` will error out (I'll verify this), but it could also be that some dependency already in the package-set is missing some of their dependencies. 

We have #24 open for a proposal to add a `from-bower` command, that will fetch the bower file do this addition automagically for you.

P.S.: if you manage to find a combination of libraries that works, please consider adding them to [spacchetti](https://github.com/spacchetti/spacchetti) :)

**Comment by justinwoo** [comment]
As Fabrizio pointed out, we can't even use bower.json as a reliable source of information of what packages are required. I run into this quite often when updating package sets.

In the end, you should try to add packages to a package set (Spacchetti, a fork of Spacchetti, etc) as much as you can. Otherwise, local additions will have to try to specify their dependencies explicitly or you will just have to add them to your own dependencies list.

**Comment by naglalakk** [comment]
Hi @f-f @justinwoo. Thank you both for you answers. Ok good to know. Exciting to hear about the from-bower proposal. Overall I'm really thankful for this package because of the additions/overrides thing. It's fantastic. I will close this issue now. Thanks again to both of you for good work 👍
