### ISSUE TITLE
segmentation fault with argonaut and  affjax installs on Ubuntu

### ISSUE THREAD

**Issue by Ebmtranceboy** [spacchetti/spago#520]
With spago version 0.12.1.0, I have a segmentation fault during the installations of purescript-argonaut and purescript-random. These are happening just after 'spago init' on a fresh new project

Linux kernel : 4.15.0-72-generic
Ubuntu :  18.04.3 LTS
npm : 6.13.2

PS: Installations with bower work as expected.

Edit: segmentation fault with purescript-affjax also
Edit2 : segmentation fault on random happens only if I try  (and fail) to install argonaut first.
`spago init`
`spago install random`
works as expected.
`spago init`
`spago install argonaut`
fails.
`spago init`
`spago install affjax`
fails.

**Comment by f-f** [comment]
@Ebmtranceboy unfortunately I don't seem to be able to replicate this one. Does it happen consistently on your machine?

**Comment by Ebmtranceboy** [comment]
I'm not sure to see what you mean by consistently. It sure happens constantly (I've checked again) with argonaut and affjax, no exception.
What is different each time is the position of the segmentation fault during installation process. For instance, trying a first time produces:

$ spago -v install argonaut

> Running `getGlobalCacheDir`
> [debug] Running `spago install`
> [debug] Transformed config is the same as the read one, not overwriting it
> [debug] Ensuring that the package set is frozen
> [debug] Getting transitive deps
> [debug] Running `fetchPackages`
> [debug] Checking if `purs` is up to date
> [info] Installing 50 dependencies.
> [debug] Running `getMetadata`
> [debug] Global cache directory: "/home/joel/.cache/spago"
> [info] Searching for packages cache metadata..
> [info] Recent packages cache metadata found, using it..
> [debug] Fetching package argonaut
> [debug] Fetching package console
> [debug] Fetching package argonaut-codecs
> [debug] Fetching package const
> [debug] Fetching package arrays
> [debug] Fetching package contravariant
> [debug] Fetching package exists
> [debug] Fetching package control
> [debug] Fetching package foldable-traversable
> [debug] Fetching package distributive
> [debug] Fetching package foreign-object
> [debug] Fetching package effect
> [debug] Fetching package functions
> [debug] Fetching package either
> [debug] Fetching package argonaut-traversals
> [debug] Fetching package enums
> [debug] Fetching package functors
> [debug] Fetching package exceptions
> [debug] Fetching package argonaut-core
> [debug] Fetching package bifunctors
> [info] Copying from global cache: "console"
> [info] Copying from global cache: "argonaut-codecs"
> [info] Copying from global cache: "const"
> [info] Copying from global cache: "arrays"
> [info] Copying from global cache: "contravariant"
> [info] Copying from global cache: "exists"
> [debug] Running `globallyCache`: PackageName {packageName = "argonaut"} https://github.com/purescript-contrib/purescript-argonaut.git v6.0.0
> [info] Copying from global cache: "control"
> [info] Copying from global cache: "distributive"
> [info] Copying from global cache: "foldable-traversable"
> [info] Copying from global cache: "foreign-object"
> [info] Copying from global cache: "effect"
> [info] Copying from global cache: "either"
> [info] Copying from global cache: "functions"
> [info] Copying from global cache: "enums"
> [info] Copying from global cache: "exceptions"
> [info] Copying from global cache: "functors"
> [debug] Running `globallyCache`: PackageName {packageName = "argonaut-traversals"} https://github.com/purescript-contrib/purescript-argonaut-traversals.git v7.0.0
> [info] Copying from global cache: "argonaut-core"
> [info] Copying from global cache: "bifunctors"
> [debug] Fetching package gen
> [debug] Fetching package globals
> [debug] Fetching package identity
> [debug] Fetching package lists
> [debug] Fetching package math
> [debug] Fetching package maybe
> [debug] Fetching package newtype
> [debug] Fetching package nonempty
> [info] Copying from global cache: "gen"
> [debug] Fetching package invariant
> [debug] Fetching package lazy
> [debug] Fetching package integers
> [info] Copying from global cache: "globals"
> [debug] Fetching package ordered-collections
> [debug] Fetching package orders
> [debug] Fetching package partial
> [debug] Fetching package prelude
> [info] Copying from global cache: "identity"
> [info] Copying from global cache: "lists"
> [info] Copying from global cache: "math"
> [debug] About to fetch tarball for https://github.com/purescript-contrib/purescript-argonaut/archive/v6.0.0.tar.gz
> [debug] About to fetch tarball for https://github.com/purescript-contrib/purescript-argonaut-traversals/archive/v7.0.0.tar.gz
> [info] Copying from global cache: "maybe"
> [info] Copying from global cache: "newtype"
> [debug] Fetching package profunctor
> [info] Copying from global cache: "nonempty"
> [info] Copying from global cache: "lazy"
> [info] Copying from global cache: "invariant"
> [info] Copying from global cache: "integers"
> [info] Copying from global cache: "ordered-collections"
> [info] Copying from global cache: "orders"
> [info] Copying from global cache: "partial"
> [info] Copying from global cache: "prelude"
> [debug] Fetching package profunctor-lenses
> [debug] Fetching package proxy
> [debug] Fetching https://github.com/purescript-contrib/purescript-argonaut/archive/v6.0.0.tar.gz
> [debug] Fetching https://github.com/purescript-contrib/purescript-argonaut-traversals/archive/v7.0.0.tar.gz
> [debug] Fetching package psci-support
> [debug] Fetching package record
> [info] Copying from global cache: "profunctor"
> Segmentation fault (core dumped)
> 

whereas the next produces 

$ spago -v install argonaut

> Running `getGlobalCacheDir`
> [debug] Running `spago install`
> [debug] Transformed config is the same as the read one, not overwriting it
> [debug] Ensuring that the package set is frozen
> [debug] Getting transitive deps
> [debug] Running `fetchPackages`
> [debug] Checking if `purs` is up to date
> [info] Installing 50 dependencies.
> [debug] Running `getMetadata`
> [debug] Global cache directory: "/home/joel/.cache/spago"
> [info] Searching for packages cache metadata..
> [info] Recent packages cache metadata found, using it..
> [debug] Fetching package argonaut
> [debug] Fetching package foldable-traversable
> [debug] Fetching package foreign-object
> [debug] Fetching package functions
> [debug] Fetching package functors
> [debug] Fetching package exists
> [debug] Fetching package argonaut-traversals
> [debug] Fetching package control
> [debug] Fetching package console
> [debug] Fetching package either
> [debug] Fetching package argonaut-core
> [debug] Fetching package argonaut-codecs
> [debug] Fetching package arrays
> [debug] Fetching package const
> [debug] Fetching package distributive
> [debug] Fetching package enums
> [debug] Fetching package effect
> [debug] Fetching package exceptions
> [debug] Fetching package bifunctors
> [debug] Fetching package contravariant
> [info] Copying from global cache: "foldable-traversable"
> [info] Copying from global cache: "functions"
> [info] Copying from global cache: "foreign-object"
> [info] Copying from global cache: "functors"
> [info] Copying from global cache: "exists"
> [debug] Running `globallyCache`: PackageName {packageName = "argonaut"} https://github.com/purescript-contrib/purescript-argonaut.git v6.0.0
> [info] Copying from global cache: "control"
> [info] Copying from global cache: "console"
> [info] Copying from global cache: "either"
> [debug] Running `globallyCache`: PackageName {packageName = "argonaut-traversals"} https://github.com/purescript-contrib/purescript-argonaut-traversals.git v7.0.0
> [info] Copying from global cache: "argonaut-core"
> [info] Copying from global cache: "argonaut-codecs"
> [info] Copying from global cache: "arrays"
> [info] Copying from global cache: "const"
> [info] Copying from global cache: "enums"
> [info] Copying from global cache: "distributive"
> [info] Copying from global cache: "effect"
> [info] Copying from global cache: "exceptions"
> [info] Copying from global cache: "bifunctors"
> [info] Copying from global cache: "contravariant"
> [debug] Fetching package globals
> [debug] Fetching package identity
> [debug] Fetching package gen
> [debug] Fetching package integers
> [debug] Fetching package invariant
> [debug] Fetching package lazy
> [debug] Fetching package lists
> [debug] Fetching package math
> [info] Copying from global cache: "globals"
> [info] Copying from global cache: "identity"
> [debug] Fetching package maybe
> [debug] Fetching package newtype
> [debug] Fetching package nonempty
> [debug] Fetching package ordered-collections
> [info] Copying from global cache: "gen"
> [debug] Fetching package orders
> [info] Copying from global cache: "integers"
> [debug] Fetching package partial
> [info] Copying from global cache: "invariant"
> [debug] Fetching package prelude
> [info] Copying from global cache: "lazy"
> [info] Copying from global cache: "lists"
> [info] Copying from global cache: "math"
> [debug] Fetching package profunctor
> [info] Copying from global cache: "maybe"
> [info] Copying from global cache: "newtype"
> [info] Copying from global cache: "nonempty"
> [info] Copying from global cache: "ordered-collections"
> [info] Copying from global cache: "orders"
> [info] Copying from global cache: "partial"
> [debug] About to fetch tarball for https://github.com/purescript-contrib/purescript-argonaut/archive/v6.0.0.tar.gz
> [debug] About to fetch tarball for https://github.com/purescript-contrib/purescript-argonaut-traversals/archive/v7.0.0.tar.gz
> [debug] Fetching package profunctor-lenses
> [debug] Fetching package psci-support
> [debug] Fetching package proxy
> [debug] Fetching package record
> [info] Copying from global cache: "prelude"
> [debug] Fetching package strings
> [debug] Fetching package tailrec
> [debug] Fetching package refs
> [debug] Fetching package st
> [info] Copying from global cache: "profunctor"
> [debug] Fetching package transformers
> [debug] Fetching package tuples
> [debug] Fetching package type-equality
> [debug] Fetching package typelevel-prelude
> [debug] Fetching https://github.com/purescript-contrib/purescript-argonaut/archive/v6.0.0.tar.gz
> [debug] Fetching https://github.com/purescript-contrib/purescript-argonaut-traversals/archive/v7.0.0.tar.gz
> [debug] Running `globallyCache`: PackageName {packageName = "profunctor-lenses"} https://github.com/purescript-contrib/purescript-profunctor-lenses.git v6.2.0
> [info] Copying from global cache: "psci-support"
> [info] Copying from global cache: "proxy"
> [info] Copying from global cache: "record"
> [info] Copying from global cache: "strings"
> Segmentation fault (core dumped)
>

**Comment by f-f** [comment]
@Ebmtranceboy right, it looks like the segfault happens once Spago tries to fetch the tarball. Does the problem still occur if you pass `--global-cache=skip` to `spago install`? If yes, can you post the debug output?

**Comment by Ebmtranceboy** [comment]
The problem doesn't occur if I pass the skip option :)
What does it do ?

**Comment by f-f** [comment]
@Ebmtranceboy when the global cache is enabled Spago will try to fetch `tar` archives from GitHub if it can - as they are much faster to download than doing a `git clone`, which is what happens when it cannot cache them and when you pass that flag.

So the fact that skipping the `tar` archives makes this work seems to be strong evidence that the segmentation fault is happening in the `tar` code, here:
https://github.com/spacchetti/spago/blob/426838670ba9de4593f4c533a6947efb2d8ad4ba/src/Spago/GlobalCache.hs#L151-L157

At line 154 we have the log that is being printed just before the thing crashes, and at line 157 the Tar decompression is happening. So I suspect there is a bug in one of the libraries in your system, maybe `zlib`?

Where to go from here:
- we could try to catch this and just do a `git clone` if the tar download doesn't work, but I'm not sure if we can acually catch segmentation faults?
- could you try to see if it's possible to upgrade `zlib` on your system?

**Comment by Ebmtranceboy** [comment]
I've just built zlib-1.2.11 from source and installed it after the '*** zlib 64-bit test OK ***' message from make test, so I suppose I've upgraded it. Nevertheless, how to be sure on Ubuntu ?, it appears so messy sometimes! It seems zlib1g is installed also, what is its purpose ? So many questions. That's beyond me. I don't want to dig deeper. Maybe when I'm upgrading to a whole new Ubuntu, I'll give another try. 

Anyway, that didn't help. Thanks for the --global-cache=skip suggestion, I'll stick to that for now. If you think that's an Ubuntu problem, then be it. We'll see on another release if things have improved. That's a pity no one else but me can report this problem, but as it isn't critical for me, I'm ok to close this issue if you want.

**Comment by f-f** [comment]
@Ebmtranceboy thanks for looking into this and I'm sorry this doesn't fix your issue!

Let's leave this open for now, we'll verify after we make progress on #528, which should fix this once and for all

**Comment by f-f** [comment]
@Ebmtranceboy we now have a static binary! ([here](https://github.com/spacchetti/spago/releases/download/0.13.0/linux-static.tar.gz)) Could you try it and see if it solves the issue?

**Comment by Ebmtranceboy** [comment]
Everything seems ok : I can install both argonaut and affjax without any issue.
May I ask what is the purpose of spago-curator? Is it mandatory to keep it next to the spago binary?

**Comment by f-f** [comment]
@Ebmtranceboy happy to hear this works!

The `spago-curator` tool is used by maintainers only and doesn't need to be kept next to the `spago` binary - in fact you might notice that we don't publish it in our releases. You can find more info about it [here](https://github.com/spacchetti/spago/blob/master/app/Curator.hs)

Since this seems to be solved I'll go ahead and close this, let's reopen if there's anything new on this front :slightly_smiling_face:
