### ISSUE TITLE
Some Classes not in Doc Search

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [spacchetti/spago#534]
When using the generated search the class `RowToList` is not found even though the module documentation for `Prim.RowList` has been generated.

**Comment by klntsky** [comment]
Thank you for the report!

Unfortunately, `Prim.*` modules are built-in, they don't have real sources. Pursuit, being a Haskell app, has access to their docs that are constructed specially (see https://hackage.haskell.org/package/purescript-0.13.5/docs/Language-PureScript-Docs-Prim.html)

docs-search app is written in PS and can't link to the purescript compiler to get the data from there.

**Comment by BebeSparkelSparkel** [comment]
Thanks

**Comment by klntsky** [comment]
I guess this should be moved to spacchetti/purescript-docs-search#31
