### ISSUE TITLE
fix import warnings

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [spacchetti/spago#554]
What are your thoughts on automatically fixing import warnings?

**Comment by klntsky** [comment]
Editor plugins are more fit for this task. Users don't expect a build tool to edit the sources.

**Comment by BebeSparkelSparkel** [comment]
thanks

**Comment by f-f** [comment]
@klntsky I generally agree, though I was thinking that it could be cool to have a hook for running `purty` when building - I don't know if it does fix imports, but a linter is way more fit than a build tool for this. If this makes sense we can open an issue (or repurpose this one) to track this.

**Comment by klntsky** [comment]
Perhaps most users are using npm scripts or a task runner, so they could trivially add purty to their build chain if they wanted.

We can't integrate with every tool in existence, so if we do, we need a strong incentive to. What benefits can integration with purty provide, in comparison with running purty from a task runner?

**Comment by f-f** [comment]
Right. Now that I think of it we already are a task runner since we have all the `before`/`then`/etc stuff, so I guess we should just have a way to add those to the config file
