### ISSUE TITLE
Add ability to build command to watch for file changes

### ISSUE THREAD

**Issue by alex-ketch** [spacchetti/spago#65]
Hi there, and thanks for Spago!

As I was creating a fork of a [react-basic-starter](https://github.com/alex-ketch/spago-react-basic-starter) to use Spago, I wanted to recommend a way to have the project be auto-built when making changes. 
Right now there is in a [workaround](https://github.com/alex-ketch/spago-react-basic-starter#compatability-with-ide-purescript-plugin) for people using IDE PureScript, but it would be nice to have an alternative for people who don't use the plugin.

I realize this is a little bit more complicated since Spago uses `purs` under the hood, and unlike `pulp` it doesn't support the `watch` flag.

_As an aside, the project seems to work like a treat combined with Parcel 🎉_

**Comment by justinwoo** [comment]
Personally I use either the normal psc-ide plugins or https://github.com/watchexec/watchexec

**Comment by f-f** [comment]
Hi @alex-ketch, and thank you for making the `spago-react-basic-starter`!

As Justin already noted, if you use psc-ide with some editor you get this rebuilding for free, and if you're not you can use watchexec (e.g. like `watchexec -i src spago build`).

So in the end it is possible, but not super nice (as you have to install another tool), and I agree that it might be worth to just integrate the file watching into Spago.
I probably won't get around implementing this soon, so I'll leave here a draft for a possible implementation:
- depend on [`fsnotify`](http://hackage.haskell.org/package/fsnotify)
- when the `--watch` flag is specified, watch on `src` folder and run `build` on modifications
- `fsnotify` supports debouncing (e.g. if you save the same file twice in a short amount of time, you should build only on the second time), but particular attention should be put on tweaking the debounce value, and probably it'd be necessary to have a semaphore (e.g. a `Bool` in an `MVar`) to signal if we are building, and if we should enqueue another build (as you don't want two builds going on at the same time)

**Comment by f-f** [comment]
[Here's Stack's implementation of this feature](https://github.com/commercialhaskell/stack/blob/0740444175f41e6ea5ed236cd2c53681e4730003/src/Stack/FileWatch.hs). It's 100 lines, so it should be easy to port here

**Comment by f-f** [comment]
Fix up in #126

**Comment by dlight** [comment]
So.. how do you run parcel (or some other custom command) after every time a build is triggered?

Something like this would be useful:

```
spago bundle-app --to dist/index.js --watch --run-after "parcel blabla"
```

**Comment by JordanMartinez** [comment]
@dlight I think you need to invert your thinking.

Make `parcel` watch for file changes where one of its files (say an HTML file) references the bundled app or module that spago produces (which will cause parcel to watch that file for changes, too) and then make spago bundle its app/module using its watch command.

When you make changes to your source code, spago sees the change and rebundles the app/module, which is seen by parcel and causes parcel to rebuild the page.

**Comment by dlight** [comment]
@JordanMartinez if I understand correctly, this require running two long living processes in two terminal tabs, which is what I'm trying to avoid.

A workaround is running `watchexec`, and make it run `spago` then `parcel` on each invocation.

**Comment by JordanMartinez** [comment]
Ah, with that criteria, then yeah, it requires a workaround.

**Comment by dlight** [comment]
Just in case it's useful for someone, I ended up writing this script

```#!/bin/bash

function cleanup {
    trap - SIGTERM
    kill -- -$$
}

trap cleanup SIGINT SIGTERM EXIT

rm -f dist/*

while [[ ! -f dist/app.js ]]; do sleep 0.01; done && \
    parcel serve asset index.html -o dist/index.html > \
           >(sed 's/^/(parcel): /') 2>&1 &

spago bundle-app --watch -m App -t dist/app.js #> >(sed 's/^/(spago): /') 2>&1
```

It runs Spago on the foreground to enable running commands, like `build`. Parcel hangs if there's no app.js file (even if one is created later), that's why it needs this sleep. I wanted Spago to drive Parcel in order to avoid those kinds of quirks (however, this wouldn't work with `parcel serve` anyway).

The commented out part would prefix Spago's output with `(spago):` but it doesn't work because Spago appears to not do line buffering when writing to something that isn't a tty, so nothing shows up until ctrl+d -- then everything appears at once (but Parcel works fine - just without colors - so maybe this counts as a Spago bug?)

I tried working around with `stdbuf -oL spago bundle-app --watch -m App -t dist/app.js > >(sed 's/^/(spago): /') 2>&1` but it also doesn't work.

**Comment by f-f** [comment]
@dlight just curious about your use-case: why is it a requirement to avoid running two long-lived processes for the watchers?

Also you might be interested in https://github.com/spacchetti/spago/issues/134 which discusses a possible integration with Parcel (so if that would exist you'd only need to run Parcel and it would call the relevant Spago stuff or keep a watcher and run things in order, etc)

**Comment by dlight** [comment]
@f-f I just wanted to avoid opening two terminal tabs, that's all

And, integration with Parcel sounds awesome!

**Comment by milesfrain** [comment]
> As Justin already noted, if you use psc-ide with some editor you get this rebuilding for free, and if you're not you can use watchexec (e.g. like `watchexec -i src spago build`).

Note for new readers, the `-i` "ignore" flag should be replaced with the `-w` "watch" flag.
@f-f Feel free to edit to prevent additional confusion.

I'm using a combination of these commands in separate terminals for automatic page reloading upon file changes:
* `watchexec -w src -e purs -- spago bundle-app     .......`
* `parcel serve      ........`

**Comment by windmaomao** [comment]
I used to use `nodemon` but seems not as general as `watchexec`. 

This works for me, thank you. 

```
  watchexec -w src -e purs -- spago test
```
