### ISSUE TITLE
Spago testing fails on windows

### ISSUE THREAD

**Issue by btrepp** [spacchetti/spago#91]
Running the python tests seems to fail on windows.

I'll spend some time later investigating it further.

> python ..\spago-test.py
> Expecting success from: "spago init"
> Expecting failure from: "spago init"
> Expecting success from: "rm spago.dhall packages.dhall"
> Expecting success from: "spago init"
> Expecting success from: "rm src/Main.purs"
> Expecting success from: "spago init -f"
> FAILURE: Spago should always succeed in doing init with force
> Program output:
> spago: .\packages.dhall: openFile: permission denied (Permission denied)

**Comment by f-f** [comment]
Related to this: we have the AppVeyor build for uploading Windoes releases to GitHub, but it's not running tests yet. We can add tests to the AppVeyor file with the `test_script` key, something like
```yaml
test_script:
- python3 .\spago-test.py
```

**Comment by btrepp** [comment]
https://github.com/spacchetti/spago/blob/11af3baa769ca8a02d7bcbb6f7ddf961a8a7ed1f/app/PscPackage.hs#L68-L69

Causes it, the act of touching the file and then writing to it causes this. This may be an issue with turtle, and I think it's definitely windows specific. I'd say the root here is touch locks the file for writing, and by the time we want to write to it, it's still locked. Windows file locking and writing is something I've encountered many times :(.

This has progressed the tests to

> Expecting success from: "spago init"
> Expecting failure from: "spago init"
> Expecting success from: "rm spago.dhall packages.dhall"
> Expecting success from: "spago init"
> Expecting success from: "rm src/Main.purs"
> Expecting success from: "spago init -f"
> Expecting success from: "spago init -f"
> Successfully verified fixture for "spago-psc-success.dhall"
> Expecting success from: "spago init -f"
> Successfully verified fixture for "spago-psc-failure.dhall"
> Going to run this for 0.5s: "spago install -j 3"
> Traceback (most recent call last):
>   File "..\spago-test.py", line 66, in <module>
>     run_for(0.5, ['spago', 'install', '-j', '3'])
>   File "C:\Users\Beau\Code\spago\test\utils.py", line 50, in run_for
>     process.send_signal(signal.SIGINT)
>   File "C:\Python37\lib\subprocess.py", line 1306, in send_signal
>     raise ValueError("Unsupported signal: {}".format(sig))
> ValueError: Unsupported signal: 2

Which comes from 
https://github.com/spacchetti/spago/blob/11af3baa769ca8a02d7bcbb6f7ddf961a8a7ed1f/test/utils.py#L50

Which is obviously never going to run on windows :). I'll see if I can detect windows in the tests and call the windows equivalent
