### ISSUE TITLE
Packages listed but not installed

### ISSUE THREAD

**Issue by naglalakk** [spacchetti/spago#92]
Hi. I'm adding purescript-express as an addition in packages.dhall like so

```
let additions = 
  { express  = 
      mkPackage 
      [ "foreign"
      , "foreign-generic"
      , "node-http"
      , "test-unit"
      , "aff"
      ]
      "https://github.com/nkly/purescript-express"
      "master"
  }
```

Then I do spago install. Now when doing 

```
spago list-packages | grep express
```

I get 

```
express (master, https://github.com/nkly/purescript-express)
```

But when I do spago build I get

```
Error 1 of 4:

  in module Server
  at src/Server.purs line 6, column 1 - line 6, column 61

    Module Node.Express.App was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.
```
also when verifying the location of the package: spago sources | grep express
i get nothing.

does this have something to do with the verification of a package? and if it fails it will do so silently?

**Comment by naglalakk** [comment]
hahaha damn of course!. Silly me. Thank you so much for a quick response @f-f

**Comment by f-f** [comment]
You're welcome! 🙂

**Comment by f-f** [comment]
Btw @naglalakk be careful with adding a package pointing to a branch: if more commits are added to the branch spago won't pick them up unless you remove the `.spago` folder and install again (we have a few more words about this [here](https://github.com/spacchetti/spago#adding-and-overriding-dependencies))

So if you can you should use tags (the support for pinning to single commits is underway)

**Comment by naglalakk** [comment]
I actually knew about this. I was just so sure I was doing something wrong that I didn't consider this to be the problem. I searched this whole issue tracker to be sure I wasn't duplicating the issue lol. This is totally my own fault. I think the FAQ is quite clear on this actually and it totally makes sense. I think it's more that I need to take a break. If this hasn't been an issue for many users I don't think it's a problem at all.

Yeah good point. I originally used a version tag but changed to master in my quest of finding out what was wrong.
